import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { createClient } from "@supabase/supabase-js";
import { updateRedemptionMessage } from "@/lib/telegram-redemption";
const URL=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://glkpxyanjsktmwkvvsxt.supabase.co";
function db(req:NextRequest){const key=process.env.SUPABASE_SERVICE_ROLE_KEY,raw=req.cookies.get("viewcash_admin")?.value;if(!key||!raw)return null;const [id,t,s]=raw.split(".");if(!id||!t||!s)return null;const age=Date.now()-Number(t);if(!/^\d+$/.test(id)||!/^\d+$/.test(t)||age<0||age>8*60*60*1000)return null;const e=crypto.createHmac("sha256",key).update(`${id}.${t}`).digest("hex");if(s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;return createClient(URL,key,{auth:{autoRefreshToken:false,persistSession:false}});}
export async function GET(req:NextRequest){const d=db(req);if(!d)return NextResponse.json({error:"ADMIN_ACCESS_DENIED"},{status:403});const {data,error}=await d.from("data_redemptions").select("id,user_id,network,phone_number,amount_mb,balance_type,status,provider_reference,admin_note,created_at,processed_at,users(username,first_name,last_name)").order("created_at",{ascending:false});if(error)return NextResponse.json({error:"ADMIN_REDEMPTIONS_ERROR"},{status:500});return NextResponse.json({redemptions:(data||[]).map((x:any)=>({...x,username:x.users?.username||null}))});}
export async function PATCH(req:NextRequest){const d=db(req);if(!d)return NextResponse.json({error:"ADMIN_ACCESS_DENIED"},{status:403});const b=await req.json().catch(()=>null);const id=String(b?.id||"");const status=String(b?.status||"");if(!id||!["pending","approved","completed","rejected"].includes(status))return NextResponse.json({error:"INVALID_REDEMPTION_UPDATE"},{status:400});const {data:row,error}=await d.from("data_redemptions").select("id,status,telegram_message_id,user_id,network,phone_number,amount_mb,created_at").eq("id",id).single();if(error||!row)return NextResponse.json({error:"REDEMPTION_NOT_FOUND"},{status:404});const {data,error:up}=await d.from("data_redemptions").update({status,admin_note:b?.admin_note==null?null:String(b.admin_note),processed_at:["completed","rejected"].includes(status)?new Date().toISOString():null}).eq("id",id).select().single();if(up)return NextResponse.json({error:"ADMIN_REDEMPTION_UPDATE_ERROR"},{status:500});
  if(row.telegram_message_id && row.status!==status){
    const {data:profile}=await d.from("users").select("username,first_name").eq("id",row.user_id).maybeSingle();
    const {count}=await d.from("data_redemptions").select("id",{count:"exact",head:true}).eq("user_id",row.user_id).lte("created_at",row.created_at);
    try{await updateRedemptionMessage(Number(row.telegram_message_id),{id:String(row.id),username:profile?.username,firstName:profile?.first_name,amountMb:Number(row.amount_mb),network:row.network,phoneNumber:row.phone_number,redemptionNumber:Number(count||1),status});}catch(telegramError){console.error("Telegram redemption status update failed:",telegramError);}
  }
  return NextResponse.json({redemption:data});}