"use client";
import { useEffect, useState } from "react";
import { LayoutDashboard, Users, CirclePlay, ClipboardList, WalletCards, ShieldAlert, Settings, LogOut } from "lucide-react";

const items=[["Dashboard",LayoutDashboard],["Users",Users],["Ads",CirclePlay],["Tasks",ClipboardList],["Withdrawals",WalletCards],["Fraud / Risk",ShieldAlert],["Settings",Settings]];
const defaults={ad_reward:0,ad_reward_coins:100,daily_ad_limit:20,ad_cooldown_seconds:30,coin_cash_rate_cash:100,coin_cash_rate_coins:1000,minimum_withdrawal:1000,minimum_withdrawal_coins:10000,activation_fee:1000,referral_reward:0,referral_reward_coins:100,referral_requires_activation:true,task_reward_coins:0,welcome_bonus_coins:100,admin_telegram_id:7160561113,fraud_max_ads_per_minute:3,fraud_max_tasks_per_minute:5,fraud_max_withdrawals_per_day:2,fraud_auto_suspend_critical:true,fraud_block_duplicate_reward_events:true,fraud_flag_rapid_activity:true};
const settingFields=[
 ["ad_reward","Reward per valid ad"],["ad_reward_coins","Reward coins per valid ad"],["daily_ad_limit","Daily ad limit"],["ad_cooldown_seconds","Ad cooldown (seconds)"],
 ["minimum_withdrawal","Legacy minimum withdrawal"],["minimum_withdrawal_coins","Legacy minimum withdrawal (coins)"],["activation_fee","Default activation fee"],["referral_reward","Referral reward"],["referral_reward_coins","Referral reward (coins)"],["task_reward_coins","Task reward (coins)"],["welcome_bonus_coins","Welcome bonus (coins)"],["admin_telegram_id","Admin Telegram ID"],
 ["fraud_max_ads_per_minute","Max ads per minute"],["fraud_max_tasks_per_minute","Max tasks per minute"],["fraud_max_withdrawals_per_day","Max withdrawals per day"]
];
const toggleFields=[["referral_requires_activation","Referral requires activation"],["fraud_auto_suspend_critical","Auto-suspend critical fraud"],["fraud_block_duplicate_reward_events","Block duplicate reward events"],["fraud_flag_rapid_activity","Flag rapid activity"]];

export default function AdminPage(){
 const [active,setActive]=useState("Dashboard"),[authorized,setAuthorized]=useState(false),[message,setMessage]=useState("Checking admin access..."),[stats,setStats]=useState({users:0,ads:0,withdrawals:0,flagged:0}),[settings,setSettings]=useState(defaults),[saved,setSaved]=useState(""),[saving,setSaving]=useState(false);
 const [users,setUsers]=useState([]),[search,setSearch]=useState(""),[tasks,setTasks]=useState([]),[withdrawals,setWithdrawals]=useState([]),[withdrawalMessage,setWithdrawalMessage]=useState(""),[withdrawalBusy,setWithdrawalBusy]=useState(null);
 const [taskTitle,setTaskTitle]=useState(""),[taskDescription,setTaskDescription]=useState(""),[taskReward,setTaskReward]=useState(0),[taskType,setTaskType]=useState("manual"),[taskUrl,setTaskUrl]=useState(""),[taskDaily,setTaskDaily]=useState(""),[taskCompletion,setTaskCompletion]=useState(""),[taskMessage,setTaskMessage]=useState(""),[taskSaving,setTaskSaving]=useState(false);
 useEffect(()=>{(async()=>{try{const tg=window.Telegram?.WebApp;if(!tg?.initData){setMessage("Open the Admin Panel from Telegram.");return;}tg.ready?.();tg.expand?.();const auth=await fetch("/api/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:tg.initData}),cache:"no-store"});if(!auth.ok){setMessage((await auth.json().catch(()=>({}))).error||"Admin access denied.");return;}setAuthorized(true);const [a,b]=await Promise.all([fetch("/api/admin/stats",{cache:"no-store"}),fetch("/api/admin/settings",{cache:"no-store"})]);if(a.ok)setStats(await a.json());if(b.ok){const d=await b.json();setSettings(x=>({...x,...d,coin_cash_rate_cash:Number(d.coin_cash_rate?.cash??x.coin_cash_rate_cash),coin_cash_rate_coins:Number(d.coin_cash_rate?.coins??x.coin_cash_rate_coins)}));}setMessage("");}catch{setMessage("Unable to verify admin access.");}})();},[]);
 useEffect(()=>{if(!authorized||active!=="Users")return;fetch(`/api/admin/users${search?`?search=${encodeURIComponent(search)}`:""}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>d&&setUsers(d.users||[])).catch(()=>{});},[authorized,active,search]);
 useEffect(()=>{if(!authorized||active!=="Tasks")return;loadTasks();},[authorized,active]);
 useEffect(()=>{if(!authorized||active!=="Withdrawals")return;loadWithdrawals();},[authorized,active]);
 const loadTasks=async()=>{const r=await fetch("/api/admin/tasks",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setTasks(d.tasks||[]);};
 const loadWithdrawals=async()=>{setWithdrawalMessage("");const r=await fetch("/api/admin/withdrawals",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setWithdrawals(d.withdrawals||[]);else setWithdrawalMessage(d.error||"Unable to load withdrawals.");};
 const updateWithdrawal=async(w,status)=>{setWithdrawalBusy(w.id);try{const r=await fetch("/api/admin/withdrawals",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:w.id,status,admin_note:w.admin_note||null})});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||"Unable to update withdrawal");await loadWithdrawals();}catch(e){setWithdrawalMessage(e.message||"Unable to update withdrawal");}finally{setWithdrawalBusy(null);}};
 const saveNote=async(w,note)=>{const r=await fetch("/api/admin/withdrawals",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:w.id,status:w.status,admin_note:note})});if(r.ok)setWithdrawals(x=>x.map(y=>y.id===w.id?{...y,admin_note:note}:y));};
 const createTask=async()=>{setTaskSaving(true);setTaskMessage("");try{const r=await fetch("/api/admin/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:taskTitle,description:taskDescription,reward:taskReward,task_type:taskType,action_url:taskUrl,daily_limit:taskDaily,completion_limit:taskCompletion,status:"active"})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to create task");setTaskTitle("");setTaskDescription("");setTaskReward(0);setTaskUrl("");setTaskDaily("");setTaskCompletion("");setTaskMessage("Task created successfully.");await loadTasks();}catch(e){setTaskMessage(e.message||"Unable to create task");}finally{setTaskSaving(false);}};
 const toggleTask=async t=>{const r=await fetch("/api/admin/tasks",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:t.id,status:t.status==="active"?"inactive":"active"})});if(r.ok)loadTasks();};
 const deleteTask=async t=>{if(!window.confirm(`Delete task "${t.title}"?`))return;const r=await fetch(`/api/admin/tasks?id=${encodeURIComponent(t.id)}`,{method:"DELETE"});if(r.ok)loadTasks();};
 const saveSettings=async()=>{setSaving(true);setSaved("");try{const payload={...settings,coin_cash_rate:{cash:Number(settings.coin_cash_rate_cash),coins:Number(settings.coin_cash_rate_coins)}};delete payload.coin_cash_rate_cash;delete payload.coin_cash_rate_coins;const r=await fetch("/api/admin/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to save settings");setSaved("All settings saved successfully.");}catch(e){setSaved(e.message||"Unable to save settings.");}finally{setSaving(false);}};
 const signOut=async()=>{try{await fetch("/api/admin/logout",{method:"POST",cache:"no-store"});}finally{window.location.href="/admin";}};
 const cashRate=Number(settings.coin_cash_rate_cash)||0, coinRate=Number(settings.coin_cash_rate_coins)||0;
 const coinsToCash=(Number(settings.ad_reward_coins)||0)*(cashRate/coinRate||0);
 if(!authorized)return <main className="flex min-h-screen items-center justify-center bg-[#080d18] px-6 text-center text-white"><div><h1 className="text-3xl font-extrabold">View<span className="text-cyan-400">Cash</span></h1><p className="mt-3 text-slate-400">{message}</p></div></main>;
 return <main className="min-h-screen bg-[#080d18] text-white md:flex"><aside className="hidden w-64 shrink-0 border-r border-white/10 bg-[#0b1120] p-5 md:block"><h1 className="text-2xl font-extrabold">View<span className="text-cyan-400">Cash</span></h1><p className="mt-1 text-xs text-slate-500">Admin Panel</p><nav className="mt-8 space-y-1">{items.map(([label,Icon])=><button key={label} onClick={()=>setActive(label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm ${active===label?"bg-cyan-400/10 text-cyan-300":"text-slate-400 hover:bg-white/5"}`}><Icon size={18}/>{label}</button>)}</nav><button onClick={signOut} className="mt-8 flex items-center gap-3 px-3 py-3 text-sm text-slate-500"><LogOut size={18}/>Sign out</button></aside><section className="mx-auto w-full max-w-6xl p-5 md:p-8"><div className="mb-5 flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-[#0b1120] p-2 md:hidden">{items.map(([label,Icon])=><button key={label} onClick={()=>setActive(label)} className={`flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-xs font-semibold ${active===label?"bg-cyan-400/10 text-cyan-300":"text-slate-400"}`}><Icon size={15}/>{label}</button>)}</div><header className="mb-7"><p className="text-sm text-slate-500">ViewCash control center</p><h2 className="mt-1 text-3xl font-extrabold">{active}</h2></header>
 {active==="Dashboard"&&<><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Card title="Users" value={String(stats.users)} icon={<Users/>}/><Card title="Ads watched" value={String(stats.ads)} icon={<CirclePlay/>}/><Card title="Pending withdrawals" value={String(stats.withdrawals)} icon={<WalletCards/>}/><Card title="Risk flags" value={String(stats.flagged)} icon={<ShieldAlert/>}/></div><div className="mt-6 rounded-3xl border border-white/10 bg-white/[.035] p-5"><h3 className="font-bold">Admin controls</h3><p className="mt-2 text-sm leading-6 text-slate-400">Manage users, rewarded ads, tasks, withdrawals, fraud controls and platform settings from here.</p></div></>}
 {active==="Users"&&<section><input value={search} onChange={e=>setSearch(e.target.value)} className="field mb-4" placeholder="Search username or name"/><div className="space-y-3">{users.map(u=>{const w=Array.isArray(u.wallets)?u.wallets[0]:u.wallets;return <div key={u.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-start justify-between"><div><p className="font-bold">{u.username?`@${u.username}`:u.first_name||"Telegram User"}</p><p className="text-xs text-slate-500">{u.first_name||""} {u.last_name||""}</p></div><span className="rounded-full bg-cyan-400/10 px-2 py-1 text-xs text-cyan-300">{u.status}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Stat label="Balance" value={`₦${Number(w?.balance||0).toFixed(2)}`}/><Stat label="Referral" value={`₦${Number(w?.referral_balance||0).toFixed(2)}`}/></div></div>})}{users.length===0&&<Empty text="No users found."/>}</div></section>}
 {active==="Ads"&&<section className="max-w-3xl"><div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><h3 className="text-xl font-bold">Rewarded Ads</h3><p className="mt-2 text-sm text-slate-400">Provider rewards, daily limits and cooldown are editable under Settings. Plan-specific reward and ad limits are under Plans.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["ad_reward","Reward per valid ad"],["ad_reward_coins","Reward coins per valid ad"],["daily_ad_limit","Daily ad limit"],["ad_cooldown_seconds","Cooldown seconds"]].map(([k,l])=><Field key={k} label={l} value={settings[k]} onChange={v=>setSettings(s=>({...s,[k]:v}))}/>)}</div><button onClick={saveSettings} className="mt-5 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Save Ad Settings</button></div></section>}
 {active==="Tasks"&&<section><div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><h3 className="text-xl font-bold">Create Task</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Title" text value={taskTitle} onChange={setTaskTitle}/><Field label="Reward" value={taskReward} onChange={setTaskReward}/><Field label="Action URL" text value={taskUrl} onChange={setTaskUrl}/><Field label="Daily limit" text value={taskDaily} onChange={setTaskDaily}/><Field label="Completion limit" text value={taskCompletion} onChange={setTaskCompletion}/><label className="block"><span className="text-sm text-slate-400">Task type</span><select value={taskType} onChange={e=>setTaskType(e.target.value)} className="field mt-2"><option value="manual">Manual</option><option value="link">Link</option><option value="social">Social</option></select></label></div><textarea value={taskDescription} onChange={e=>setTaskDescription(e.target.value)} className="field mt-3 min-h-24" placeholder="Description"/><button disabled={taskSaving} onClick={createTask} className="mt-4 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">{taskSaving?"Creating...":"Create Task"}</button>{taskMessage&&<p className="mt-3 text-sm text-slate-400">{taskMessage}</p>}</div><div className="mt-5 space-y-3">{tasks.map(t=><div key={t.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{t.title}</p><p className="mt-1 text-xs text-slate-500">Reward: {t.reward} · Completed: {t.completed_count||0} · Status: {t.status}</p></div><div className="flex gap-2"><button onClick={()=>toggleTask(t)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{t.status==="active"?"Disable":"Enable"}</button><button onClick={()=>deleteTask(t)} className="rounded-lg border border-red-400/20 px-3 py-2 text-xs text-red-300">Delete</button></div></div></div>)}{tasks.length===0&&<Empty text="No tasks found."/>}</div></section>}
 {active==="Withdrawals"&&<section><p className="mb-4 text-sm text-slate-400">Review and update withdrawal requests.</p>{withdrawalMessage&&<p className="mb-3 text-sm text-red-300">{withdrawalMessage}</p>}<div className="space-y-3">{withdrawals.map(w=><div key={w.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{w.username||w.user_id}</p><p className="text-sm text-slate-400">{w.amount??w.coins??0} · {w.status}</p></div><div className="flex gap-2"><button disabled={withdrawalBusy===w.id} onClick={()=>updateWithdrawal(w,"approved")} className="rounded-lg bg-emerald-400 px-3 py-2 text-xs font-bold text-slate-950">Approve</button><button disabled={withdrawalBusy===w.id} onClick={()=>updateWithdrawal(w,"rejected")} className="rounded-lg border border-red-400/20 px-3 py-2 text-xs text-red-300">Reject</button></div></div><input defaultValue={w.admin_note||""} onBlur={e=>saveNote(w,e.target.value)} className="field mt-3" placeholder="Admin note"/></div>)}{withdrawals.length===0&&<Empty text="No withdrawals found."/>}</div></section>}
 {active==="Fraud / Risk"&&<section className="max-w-3xl"><div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><h3 className="text-xl font-bold">Fraud / Risk controls</h3><div className="mt-5 grid gap-4 sm:grid-cols-2">{settingFields.filter(([k])=>k.startsWith("fraud_")).map(([k,l])=><Field key={k} label={l} value={settings[k]} onChange={v=>setSettings(s=>({...s,[k]:v}))}/>)}{toggleFields.filter(([k])=>k.startsWith("fraud_")).map(([k,l])=><Toggle key={k} label={l} value={settings[k]} onChange={v=>setSettings(s=>({...s,[k]:v}))}/>)}</div><button onClick={saveSettings} className="mt-5 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Save Risk Settings</button></div></section>}
 {active==="Settings"&&<section className="max-w-4xl"><div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><h3 className="text-xl font-bold">Platform Settings</h3><div className="mt-5 rounded-2xl border border-cyan-400/20 bg-cyan-400/5 p-4"><p className="font-bold text-cyan-200">Coin Conversion Rate</p><p className="mt-1 text-xs leading-5 text-slate-400">Set either side and the other value updates automatically. Example: 1,000 coins = 100 balance.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Balance value" value={settings.coin_cash_rate_cash} onChange={v=>{const cash=Number(v)||0;const ratio=coinRate>0?cash/coinRate:0;setSettings(s=>({...s,coin_cash_rate_cash:cash,coin_cash_rate_coins:s.coin_cash_rate_coins}));}}/><Field label="Coins" value={settings.coin_cash_rate_coins} onChange={v=>{const coins=Number(v)||0;setSettings(s=>({...s,coin_cash_rate_coins:coins,coin_cash_rate_cash:cashRate}));}}/></div><div className="mt-4 rounded-xl bg-black/20 p-3 text-center text-sm font-bold text-cyan-200">{Number(settings.coin_cash_rate_coins||0).toLocaleString()} coins = {Number(settings.coin_cash_rate_cash||0).toLocaleString()} balance</div><div className="mt-2 rounded-xl bg-white/5 p-3 text-center text-xs text-slate-300">Current ad reward: {Number(settings.ad_reward_coins||0).toLocaleString()} coins = {coinsToCash.toLocaleString(undefined,{maximumFractionDigits:2})} balance per ad</div></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{settingFields.filter(([k])=>!k.startsWith("fraud_")).map(([k,l])=><Field key={k} label={l} value={settings[k]} onChange={v=>setSettings(s=>({...s,[k]:v}))}/>)}{toggleFields.filter(([k])=>!k.startsWith("fraud_")).map(([k,l])=><Toggle key={k} label={l} value={settings[k]} onChange={v=>setSettings(s=>({...s,[k]:v}))}/>)}</div><a href="/admin/plans" className="mt-5 inline-block rounded-xl border border-cyan-400/30 px-5 py-3 font-bold text-cyan-200">Manage Activation Plans</a><button disabled={saving} onClick={saveSettings} className="ml-3 mt-5 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">{saving?"Saving...":"Save All Settings"}</button>{saved&&<p className="mt-3 text-sm text-cyan-200">{saved}</p>}</div></section>}
 </section></main>;
}
function Card({title,value,icon}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="text-cyan-300">{icon}</div><p className="mt-3 text-xs text-slate-500">{title}</p><p className="mt-1 text-2xl font-extrabold">{value}</p></div>}
function Stat({label,value}){return <div className="rounded-xl bg-black/20 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>}
function Empty({text}){return <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">{text}</div>}
function Field({label,value,onChange,text=false}){return <label className="block"><span className="text-sm text-slate-400">{label}</span><input type={text?"text":"number"} value={value??""} onChange={e=>onChange(text?e.target.value:Number(e.target.value))} className="field mt-2"/></label>}
function Toggle({label,value,onChange}){return <label className="flex items-center justify-between rounded-2xl border border-white/10 p-4 text-sm text-slate-300"><span>{label}</span><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)} className="h-5 w-5"/></label>}
