"use client";

import { useEffect, useState } from "react";

const defaults={ad_reward:0,ad_reward_coins:100,daily_ad_limit:20,ad_cooldown_seconds:30,coin_cash_rate_cash:100,coin_cash_rate_coins:1000,minimum_withdrawal:1000,minimum_withdrawal_coins:10000,activation_fee:1000,referral_reward:0,referral_reward_coins:100,referral_requires_activation:true,task_reward_coins:0,welcome_bonus_coins:100,admin_telegram_id:7160561113,fraud_max_ads_per_minute:3,fraud_max_tasks_per_minute:5,fraud_max_withdrawals_per_day:2,fraud_auto_suspend_critical:true,fraud_block_duplicate_reward_events:true,fraud_flag_rapid_activity:true};
const fields=[
 ["ad_reward","Reward per valid ad"],["ad_reward_coins","Reward coins per valid ad"],["daily_ad_limit","Daily ad limit"],["ad_cooldown_seconds","Ad cooldown (seconds)"],
 ["coin_cash_rate_cash","Cash value in coin conversion"],["coin_cash_rate_coins","Coins used in conversion"],["minimum_withdrawal","Legacy minimum withdrawal"],["minimum_withdrawal_coins","Legacy minimum withdrawal (coins)"],
 ["activation_fee","Default activation fee"],["referral_reward","Referral reward"],["referral_reward_coins","Referral reward (coins)"],["task_reward_coins","Task reward (coins)"],["welcome_bonus_coins","Welcome bonus (coins)"],["admin_telegram_id","Admin Telegram ID"],
 ["fraud_max_ads_per_minute","Max ads per minute"],["fraud_max_tasks_per_minute","Max tasks per minute"],["fraud_max_withdrawals_per_day","Max withdrawals per day"]
];
const toggles=[["referral_requires_activation","Referral requires activation"],["fraud_auto_suspend_critical","Auto-suspend critical fraud"],["fraud_block_duplicate_reward_events","Block duplicate reward events"],["fraud_flag_rapid_activity","Flag rapid activity"]];

export default function AdminPage(){
 const [ok,setOk]=useState(false),[msg,setMsg]=useState("Checking admin access..."),[s,setS]=useState(defaults),[saving,setSaving]=useState(false),[saved,setSaved]=useState("");
 useEffect(()=>{(async()=>{try{const tg=window.Telegram?.WebApp;if(!tg?.initData){setMsg("Open the Admin Panel from Telegram.");return;}tg.ready?.();tg.expand?.();const auth=await fetch("/api/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:tg.initData}),cache:"no-store"});if(!auth.ok){setMsg((await auth.json().catch(()=>({}))).error||"Admin access denied.");return;}const r=await fetch("/api/admin/settings",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setS(x=>({...x,...d,coin_cash_rate_cash:Number(d.coin_cash_rate?.cash??x.coin_cash_rate_cash),coin_cash_rate_coins:Number(d.coin_cash_rate?.coins??x.coin_cash_rate_coins)}));setOk(true);setMsg("");}catch{setMsg("Unable to verify admin access.");}})();},[]);
 const save=async()=>{setSaving(true);setSaved("");try{const r=await fetch("/api/admin/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(s)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to save settings");setSaved("All settings saved successfully.");}catch(e){setSaved(e.message||"Unable to save settings.");}finally{setSaving(false);}};
 if(!ok)return <main className="flex min-h-screen items-center justify-center bg-[#080d18] px-6 text-center text-white"><div><h1 className="text-3xl font-extrabold">View<span className="text-cyan-400">Cash</span></h1><p className="mt-3 text-slate-400">{msg}</p></div></main>;
 return <main className="min-h-screen bg-[#080d18] px-4 py-6 text-white"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-between gap-3"><div><h1 className="text-3xl font-extrabold">View<span className="text-cyan-400">Cash</span></h1><p className="mt-1 text-sm text-slate-500">Admin Control Center</p></div><a href="/admin/plans" className="rounded-xl border border-cyan-400/30 px-3 py-2 text-sm font-bold text-cyan-300">Plans</a></div><section className="mt-6 rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-xl font-bold">All Platform Settings</h2><p className="mt-2 text-sm leading-6 text-slate-400">Change the operational values from here without editing the code.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map(([key,label])=><label key={key}><span className="text-sm text-slate-400">{label}</span><input type="number" min="0" step="0.01" value={s[key]??0} onChange={e=>setS(x=>({...x,[key]:Number(e.target.value)}))} className="field mt-2"/></label>)}</div></section><section className="mt-5 rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-xl font-bold">Rules & Security</h2><div className="mt-5 space-y-3">{toggles.map(([key,label])=><label key={key} className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-black/10 p-4"><span className="font-semibold">{label}</span><input type="checkbox" checked={Boolean(s[key])} onChange={e=>setS(x=>({...x,[key]:e.target.checked}))} className="h-5 w-5"/></label>)}</div></section><button disabled={saving} onClick={save} className="mt-5 w-full rounded-2xl bg-cyan-400 py-3.5 font-extrabold text-slate-950 disabled:opacity-50">{saving?"Saving...":"Save All Settings"}</button>{saved&&<p className="mt-3 text-center text-sm text-slate-400">{saved}</p>}<div className="mt-5 rounded-2xl border border-white/10 bg-white/[.025] p-4 text-sm text-slate-500">Activation plan names, daily earning caps, plan fees, task withdrawal minimums, affiliate withdrawal minimums and plan availability are managed separately under Plans.</div></div></main>;
}
