"use client";
import { useEffect,useState } from "react";

type Task={id:string;title:string;description:string|null;reward:number;task_type:string;action_url:string|null;verification_type:string;proof_required:boolean;completed_count:number};
export default function TasksPage(){
 const [initData,setInitData]=useState(""),[tasks,setTasks]=useState<Task[]>([]),[message,setMessage]=useState("Loading tasks..."),[busy,setBusy]=useState<string|null>(null),[proofs,setProofs]=useState<Record<string,string>>({});
 useEffect(()=>{const tg=window.Telegram?.WebApp;if(!tg?.initData){setMessage("Open ViewCash from Telegram.");return}tg.ready?.();tg.expand?.();setInitData(tg.initData);load(tg.initData)},[]);
 const load=async(data:string)=>{try{const r=await fetch(`/api/tasks?initData=${encodeURIComponent(data)}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok){setTasks(d.tasks||[]);setMessage("")}else setMessage(d.error||"Unable to load tasks.")}catch{setMessage("Unable to load tasks. Please try again.")}};
 const startTask=(t:Task)=>{if(!t.action_url)return;try{const tg=window.Telegram?.WebApp;if(/^https:\/\/t\.me\//i.test(t.action_url)&&tg?.openTelegramLink){tg.openTelegramLink(t.action_url);return}window.open(t.action_url,"_blank","noopener,noreferrer")}catch{window.location.href=t.action_url}};
 const submit=async(t:Task)=>{let proof:string|null=null;if(t.verification_type!=="telegram"){proof=(proofs[t.id]||"").trim();if(!proof){setMessage("Enter your proof URL first.");return}if(!/^https?:\/\//i.test(proof)){setMessage("Proof must be a valid http or https URL.");return}}setBusy(t.id);setMessage("");try{const r=await fetch("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task_id:t.id,initData,proof_url:proof}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Task verification failed");setMessage(`Task completed: +${Number(d.reward||0).toLocaleString()} coins`);setProofs(v=>{const n={...v};delete n[t.id];return n});await load(initData)}catch(e){setMessage(e instanceof Error?e.message:"Task verification failed")}finally{setBusy(null)}};
 return <main className="min-h-screen bg-[#070b14] px-4 py-6 text-white"><div className="mx-auto max-w-md"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">ViewCash</p><h1 className="mt-1 text-2xl font-black">Tasks</h1></div><button onClick={()=>window.location.assign("/")} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">Back</button></div>{message&&<div className="mb-4 rounded-2xl border border-cyan-300/15 bg-cyan-400/[.06] p-3 text-sm text-cyan-100">{message}</div>}<div className="space-y-3">{tasks.map(t=><article key={t.id} className="rounded-3xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.15em] text-slate-500">{t.task_type} task</p><h2 className="mt-1 font-bold">{t.title}</h2><p className="mt-1 text-sm leading-5 text-slate-400">{t.description||"Complete this task to earn coins."}</p></div><span className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-xs font-bold text-cyan-300">+{Number(t.reward).toLocaleString()}</span></div>{t.verification_type!=="telegram"&&<input className="field mt-4 w-full" value={proofs[t.id]||""} onChange={e=>setProofs(v=>({...v,[t.id]:e.target.value}))} placeholder="Paste your proof URL" inputMode="url" autoComplete="off"/>}<div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>startTask(t)} disabled={!t.action_url||busy===t.id} className="rounded-2xl border border-white/10 bg-white/[.03] py-2.5 text-sm font-semibold disabled:opacity-40">Start Task</button><button onClick={()=>submit(t)} disabled={busy===t.id} className="rounded-2xl bg-cyan-400 py-2.5 text-sm font-extrabold text-slate-950 disabled:opacity-50">{busy===t.id?"Submitting...":t.verification_type==="telegram"?"Verify":"Submit Proof"}</button></div></article>)}{!tasks.length&&<div className="rounded-3xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No tasks available right now.</div>}</div></div></main>;
}
