"use client";
import { useEffect, useRef, useState } from "react";
type MonetagResult={reward_event_type?:string}; type AdsGalaxyResult={request_id?:string;[key:string]:unknown};
declare global{interface Window{[key:`show_${string}`]:((options?:Record<string,unknown>)=>Promise<MonetagResult>)|undefined;showAdsGalaxy?:()=>Promise<AdsGalaxyResult>}}
const DEFAULT_MONETAG_ZONE="11801942", REQUIRED_VIEW_SECONDS=15, ADS_GALAXY_SCRIPT="https://app.adsgalaxy.online/sdk.js?id=92";
export default function MonetagWatch({initData}:{initData:string}){
 const [ready,setReady]=useState(false),[adsGalaxyReady,setAdsGalaxyReady]=useState(false),[busy,setBusy]=useState<"monetag"|"adsgalaxy"|null>(null),[message,setMessage]=useState("");
 const watchActiveRef=useRef(false),backGuardRef=useRef(false),activeSessionRef=useRef<{sessionId:string;requestVar:string;ymid:string}|null>(null),watchStartedAtRef=useRef(0),rewardTimerRef=useRef<number|null>(null);
 const zone=process.env.NEXT_PUBLIC_MONETAG_ZONE_ID?.trim()||DEFAULT_MONETAG_ZONE;
 useEffect(()=>{if(!zone)return;const src="https://libtl.com/sdk.js";const existing=document.querySelector(`script[data-viewcash-monetag="${zone}"]`);if(existing){const t=window.setInterval(()=>{if(typeof window[`show_${zone}`]==="function"){setReady(true);window.clearInterval(t)}},250);return()=>window.clearInterval(t)}const s=document.createElement("script");s.src=src;s.async=true;s.dataset.zone=zone;s.dataset.sdk=`show_${zone}`;s.dataset.viewcashMonetag=zone;s.onload=()=>setReady(typeof window[`show_${zone}`]==="function");document.head.appendChild(s);const t=window.setInterval(()=>{if(typeof window[`show_${zone}`]==="function"){setReady(true);window.clearInterval(t)}},250);return()=>window.clearInterval(t)},[zone]);
 useEffect(()=>{if(window.showAdsGalaxy){setAdsGalaxyReady(true);return}const existing=document.querySelector(`script[src="${ADS_GALAXY_SCRIPT}"]`);if(existing){const t=window.setInterval(()=>{if(window.showAdsGalaxy){setAdsGalaxyReady(true);window.clearInterval(t)}},250);return()=>window.clearInterval(t)}const s=document.createElement("script");s.src=ADS_GALAXY_SCRIPT;s.async=true;s.onload=()=>setAdsGalaxyReady(typeof window.showAdsGalaxy==="function");s.onerror=()=>setMessage("Ads Galaxy could not be loaded. Please try again.");document.head.appendChild(s);const t=window.setInterval(()=>{if(window.showAdsGalaxy){setAdsGalaxyReady(true);window.clearInterval(t)}},250);return()=>window.clearInterval(t)},[]);
 const cancel=async()=>{const x=activeSessionRef.current;if(!x||!initData)return;activeSessionRef.current=null;await fetch("/api/ads/cancel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,request_var:x.requestVar,ymid:x.ymid}),cache:"no-store"}).catch(()=>null)};
 useEffect(()=>{const back=()=>{if(!watchActiveRef.current||backGuardRef.current)return;backGuardRef.current=true;void cancel();window.history.pushState({viewcashAdGuard:true},"",window.location.href);setMessage("Please complete the full 15-second ad to receive your reward.");window.setTimeout(()=>{backGuardRef.current=false},100)};window.addEventListener("popstate",back);return()=>window.removeEventListener("popstate",back)},[initData]);
 const watchMonetag=async()=>{if(!initData)return setMessage("Open ViewCash from Telegram first.");const show=window[`show_${zone}`];if(!show)return setMessage("Monetag ad is not ready yet. Please try again.");setBusy("monetag");watchActiveRef.current=true;watchStartedAtRef.current=Date.now();window.history.pushState({viewcashAdGuard:true},"",window.location.href);setMessage("");try{const r=await fetch("/api/ads/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData}),cache:"no-store"});const session=await r.json().catch(()=>({}));if(!r.ok)throw new Error(session.error||"Unable to start ad.");activeSessionRef.current={sessionId:session.session_id,requestVar:session.request_var,ymid:session.ymid};const x=activeSessionRef.current;const result=await show({type:"end",ymid:session.ymid,requestVar:session.request_var,catchIfNoFeed:true});if((Date.now()-watchStartedAtRef.current)/1000<REQUIRED_VIEW_SECONDS){await cancel();setMessage("Ad was not completed. Watch the full 15 seconds to receive your reward.");return}const cr=await fetch("/api/ads/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,session_id:x.sessionId,request_var:x.requestVar,ymid:x.ymid}),cache:"no-store"});const d=await cr.json().catch(()=>({}));if(!cr.ok||!d?.ok)throw new Error(d?.error||"Your reward could not be credited yet.");setMessage(Number(d.reward_coins||0)>0?`Reward added: ${Number(d.reward_coins)} coins.`:"Ad completed. Reward already credited.");window.dispatchEvent(new CustomEvent("viewcash:wallet-updated"))}catch(e){await cancel();setMessage(e instanceof Error?e.message:"The Monetag ad could not be completed.")}finally{watchActiveRef.current=false;setBusy(null);if(rewardTimerRef.current!==null)window.clearTimeout(rewardTimerRef.current);rewardTimerRef.current=null;if(window.history.state?.viewcashAdGuard)window.history.back()}};
 const pollGalaxy=async(requestId:string)=>{for(let i=0;i<8;i++){await new Promise(r=>window.setTimeout(r,1500));const r=await fetch("/api/ads-galaxy/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,request_id:requestId}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok&&d?.credited){setMessage(`Reward added: ${Number(d.reward_coins||0)} coins.`);window.dispatchEvent(new CustomEvent("viewcash:wallet-updated"));return true}}setMessage("Ad completed. Reward confirmation is still processing.");return false};
 const watchAdsGalaxy=async()=>{if(!initData)return setMessage("Open ViewCash from Telegram first.");if(!window.showAdsGalaxy)return setMessage("Ads Galaxy is not ready yet. Please try again.");setBusy("adsgalaxy");setMessage("");try{const result=await window.showAdsGalaxy();const requestId=String(result?.request_id||"").trim();if(!requestId)throw new Error("Ads Galaxy completed without a request ID.");setMessage("Ad completed. Confirming your reward...");await pollGalaxy(requestId)}catch(e){setMessage(e instanceof Error?e.message:"The Ads Galaxy ad could not be completed.")}finally{setBusy(null)}};
 return <div className="mt-3 space-y-2.5"><button onClick={watchMonetag} disabled={busy!==null||!ready} className="w-full rounded-2xl bg-cyan-400 py-3.5 text-sm font-extrabold text-slate-950 disabled:opacity-50">{busy==="monetag"?"Watching ad...":!ready?"Loading Monetag...":"Watch Ad — Monetag"}</button><button onClick={watchAdsGalaxy} disabled={busy!==null||!adsGalaxyReady} className="w-full rounded-2xl bg-emerald-400 py-3.5 text-sm font-extrabold text-slate-950 disabled:opacity-50">{busy==="adsgalaxy"?"Watching ad...":!adsGalaxyReady?"Loading Ads Galaxy...":"Watch Ad — Ads Galaxy"}</button>{message&&<p className="rounded-2xl bg-white/[.03] px-3 py-2.5 text-xs leading-5 text-slate-400">{message}</p>}</div>;
}
