import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { createClient } from "@supabase/supabase-js";

const DAYS=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
const FREQ=["daily","weekly","monthly"];
function adminOk(req:NextRequest,secret:string){const raw=req.cookies.get("viewcash_admin")?.value;if(!raw)return false;const [id,timestamp,signature]=raw.split(".");if(!id||!timestamp||!signature||!/^[0-9]+$/.test(id)||!/^[0-9]+$/.test(timestamp))return false;const age=Date.now()-Number(timestamp);if(age<0||age>8*60*60*1000)return false;const expected=crypto.createHmac("sha256",secret).update(`${id}.${timestamp}`).digest("hex");return signature.length===expected.length&&crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected));}
function db(req:NextRequest){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||!adminOk(req,key))return null;return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});}
function normalize(raw:unknown){const s=raw&&typeof raw==="object"?raw as Record<string,unknown>:{};const days=Array.isArray(s.days)?s.days.map(String).filter(x=>DAYS.includes(x)):[];const frequency=typeof s.frequency==="string"&&FREQ.includes(s.frequency)?s.frequency:"weekly";const time=(v:unknown,f:string)=>typeof v==="string"&&/^([01]\d|2[0-3]):[0-5]\d$/.test(v)?v:f;let timezone=typeof s.timezone==="string"&&s.timezone?s.timezone:"Africa/Lagos";try{new Intl.DateTimeFormat("en-US",{timeZone:timezone}).format(new Date());}catch{timezone="Africa/Lagos";}return {enabled:s.enabled===true,frequency,days,start_time:time(s.start_time,"00:00"),end_time:time(s.end_time,"23:59"),timezone};}
export async function GET(req:NextRequest){const supabase=db(req);if(!supabase)return NextResponse.json({error:"ADMIN_ACCESS_DENIED"},{status:403});const {data,error}=await supabase.from("settings").select("key,value").in("key",["task_withdrawal_schedule","affiliate_withdrawal_schedule"]);if(error)return NextResponse.json({error:"ADMIN_WITHDRAWAL_SETTINGS_ERROR"},{status:500});const raw=Object.fromEntries((data||[]).map(r=>[r.key,r.value]));return NextResponse.json({task_withdrawal_schedule:normalize(raw.task_withdrawal_schedule),affiliate_withdrawal_schedule:normalize(raw.affiliate_withdrawal_schedule)});}
export async function POST(req:NextRequest){const supabase=db(req);if(!supabase)return NextResponse.json({error:"ADMIN_ACCESS_DENIED"},{status:403});const body=await req.json().catch(()=>null);const task=normalize(body?.task_withdrawal_schedule),affiliate=normalize(body?.affiliate_withdrawal_schedule);if((task.enabled&&!task.days.length)||(affiliate.enabled&&!affiliate.days.length))return NextResponse.json({error:"SELECT_AT_LEAST_ONE_WITHDRAWAL_DAY"},{status:400});const rows=[{key:"task_withdrawal_schedule",value:task},{key:"affiliate_withdrawal_schedule",value:affiliate}];const {error}=await supabase.from("settings").upsert(rows,{onConflict:"key"});if(error)return NextResponse.json({error:"ADMIN_WITHDRAWAL_SETTINGS_SAVE_ERROR"},{status:500});return NextResponse.json({ok:true,task_withdrawal_schedule:task,affiliate_withdrawal_schedule:affiliate});}
