"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";
import { CalendarCheck, ChevronRight, CirclePlay, ClipboardList, Copy, Gift, History as HistoryIcon, Home, Landmark, ShieldCheck, Share2, UserRound, Users, Wallet } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import MonetagWatch from "./components/monetag-watch";

type TelegramWebApp={initData:string;ready:()=>void;expand:()=>void};
declare global{interface Window{Telegram?:{WebApp?:TelegramWebApp};show_11801942?:((options?:Record<string,unknown>)=>Promise<unknown>)}}
type Section="Home"|"Watch Ads"|"Tasks"|"Wallet"|"Referral"|"Withdraw"|"History"|"Profile";
type Task={id:string;title:string;description:string|null;reward:number;task_type:string;action_url:string|null;verification_type:string;telegram_chat:string|null;completion_status?:string|null};
type HistoryItem={id:string;type:string;title:string;description:string;amount:number;balance_type:string;status:string;created_at:string};
const nav:{label:Section;icon:LucideIcon}[]=[{label:"Watch Ads",icon:CirclePlay},{label:"Tasks",icon:ClipboardList},{label:"Home",icon:Home},{label:"Referral",icon:Users},{label:"Profile",icon:UserRound}];

export default function HomePage(){
 const [active,setActive]=useState<Section>("Home"),[referralQualified,setReferralQualified]=useState(0),[referralUnlockRequired,setReferralUnlockRequired]=useState(10),[redemptionUnlocked,setRedemptionUnlocked]=useState(false),[isAdmin,setIsAdmin]=useState(false),[status,setStatus]=useState("Connecting..."),[displayName,setDisplayName]=useState(""),[initData,setInitData]=useState(""),[referralCode,setReferralCode]=useState(""),[referralLink,setReferralLink]=useState(""),[tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(false),[history,setHistory]=useState<HistoryItem[]>([]),[historyLoading,setHistoryLoading]=useState(false),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState(""),[balance,setBalance]=useState(0),[referralBalance,setReferralBalance]=useState(0);

 const refresh=useCallback(async(tg:TelegramWebApp)=>{const data=tg.initData?.trim();if(!data)throw new Error("Telegram session data is unavailable. Please reopen ViewCash from Telegram.");const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),12000);try{const r=await fetch("/api/telegram/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:data}),cache:"no-store",signal:controller.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Connection failed");setInitData(data);setDisplayName(d.display_name||"Telegram User");setReferralCode(d.referral_code||"");setReferralLink(d.referral_link||"");setBalance(Number(d.balance_mb||0));setReferralBalance(Number(d.referral_balance_mb||0));setReferralQualified(Number(d.qualified_referral_count||0));setReferralUnlockRequired(Number(d.referral_unlock_required||10));setRedemptionUnlocked(Boolean(d.redemption_unlocked));setStatus("Connected");try{const a=await fetch("/api/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:data}),cache:"no-store"});setIsAdmin(a.ok)}catch{setIsAdmin(false)}}catch(e){if(e instanceof DOMException&&e.name==="AbortError")throw new Error("Connection timed out. Please reopen ViewCash.");throw e}finally{window.clearTimeout(timeout)}},[]);

 useEffect(()=>{let dead=false,timer:number|undefined,attempts=0;const run=async()=>{if(dead)return;const tg=window.Telegram?.WebApp;if(!tg){attempts++;if(attempts<40){timer=window.setTimeout(run,250);return}setStatus("Open ViewCash from Telegram");return}try{tg.ready();tg.expand();await refresh(tg)}catch(e){if(!dead)setStatus(e instanceof Error?e.message:"Unable to connect")}};const resume=()=>{attempts=0;run()};run();window.addEventListener("pageshow",resume);const onVisibility=()=>{if(document.visibilityState==="visible")resume()};document.addEventListener("visibilitychange",onVisibility);return()=>{dead=true;if(timer)window.clearTimeout(timer);window.removeEventListener("pageshow",resume);document.removeEventListener("visibilitychange",onVisibility)}},[refresh]);

 const checkIn=async()=>{if(!initData)return setMessage("Open ViewCash from Telegram first.");setBusy("checkin");setMessage("");let session:{session_id:string;request_var:string;ymid:string}|null=null;try{const start=await fetch("/api/checkin-ad/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData}),cache:"no-store"});const s=await start.json().catch(()=>({}));if(!start.ok)throw new Error(s.error==="ALREADY_CHECKED_IN"?`Already checked in today. Streak: day ${Number(s.streak_day||1)}.`:(s.error||"Unable to start check-in ad."));session={session_id:String(s.session_id),request_var:String(s.request_var),ymid:String(s.ymid)};const zone="11801942";if(typeof window.show_11801942!=="function"){const existing=document.querySelector(`script[data-viewcash-checkin-ad="${zone}"]`);if(!existing){const script=document.createElement("script");script.src="https://libtl.com/sdk.js";script.async=true;script.dataset.zone=zone;script.dataset.sdk=`show_${zone}`;script.dataset.viewcashCheckinAd=zone;document.head.appendChild(script)}const readyAt=Date.now();while(typeof window.show_11801942!=="function"&&Date.now()-readyAt<12000)await new Promise(r=>window.setTimeout(r,250))}const show=window.show_11801942;if(!show)throw new Error("Check-in video is not ready yet. Please try again.");setMessage("Watch the full video to complete your daily check-in.");await show({type:"end",ymid:session.ymid,requestVar:session.request_var,catchIfNoFeed:true});const complete=await fetch("/api/checkin-ad/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,session_id:session.session_id,request_var:session.request_var,ymid:session.ymid}),cache:"no-store"});const d=await complete.json().catch(()=>({}));if(!complete.ok||!d?.ok){const error=String(d?.error||"CHECKIN_CREDIT_FAILED");if(error==="VIEW_TOO_SHORT")throw new Error("The video was not completed. Please watch the full video.");throw new Error(error==="ALREADY_CHECKED_IN"?`Already checked in today. Streak: day ${Number(d.streak_day||1)}.`:(d?.message||"Check-in could not be credited."))}setMessage(`Daily check-in completed. Streak: day ${Number(d.streak_day||1)}.`);if(Number(d.reward_coins||0)>0)loadHistory()}catch(e){setMessage(e instanceof Error?e.message:"Check-in failed")}finally{setBusy(null)}};
 const loadTasks=useCallback(async()=>{if(!initData)return;setLoading(true);try{const r=await fetch(`/api/tasks?initData=${encodeURIComponent(initData)}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to load tasks");setTasks(d.tasks||[])}catch(e){setMessage(e instanceof Error?e.message:"Unable to load tasks")}finally{setLoading(false)}},[initData]);
 const loadHistory=useCallback(async()=>{if(!initData)return;setHistoryLoading(true);try{const r=await fetch("/api/history",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to load history");setHistory(Array.isArray(d.history)?d.history:[])}catch(e){setMessage(e instanceof Error?e.message:"Unable to load history")}finally{setHistoryLoading(false)}},[initData]);
 useEffect(()=>{if(active==="Tasks")loadTasks()},[active,loadTasks]);
 useEffect(()=>{if(active==="History")loadHistory()},[active,loadHistory]);
 const verify=async(task:Task)=>{setBusy(task.id);setMessage("");try{const r=await fetch("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task_id:task.id,initData}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Task verification failed");setMessage("Task completed and reward recorded.");await loadTasks();loadHistory()}catch(e){setMessage(e instanceof Error?e.message:"Task verification failed")}finally{setBusy(null)}};
 const openWithdraw=()=>{window.location.assign("/withdraw")};
 const copyReferral=async()=>{if(!referralLink)return;try{await navigator.clipboard.writeText(referralLink);setMessage("Referral link copied.")}catch{setMessage("Copy failed. Long-press the link to copy it.")}};

 let content:ReactNode;
 if(active==="Watch Ads")content=<Page title="Rewards" icon={<CirclePlay size={20}/>}><div className="mb-4 rounded-2xl bg-yellow-400 p-3.5 text-black"><p className="text-[10px] font-black uppercase tracking-[.18em]">MTN Rewards</p><h3 className="mt-1 text-xl font-black">Earn MTN data rewards</h3><p className="mt-1 text-sm">Complete available activities and claim your rewards.</p></div><MonetagWatch initData={initData}/></Page>;
 else if(active==="Tasks")content=<Page title="Opportunities" icon={<ClipboardList size={20}/>} >{loading?<EmptyState title="Loading tasks" text="Finding available tasks for your account..."/>:<div className="space-y-3">{tasks.map(task=><article key={task.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-slate-500">Task</p><h3 className="mt-1 text-base font-bold">{task.title}</h3><p className="mt-1.5 text-sm leading-5 text-slate-400">{task.description||"Complete this opportunity and receive the listed reward."}</p></div><span className="shrink-0 rounded-full bg-yellow-400/15 px-2.5 py-1.5 text-[11px] font-bold text-yellow-300">Reward</span></div>{task.verification_type==="telegram"&&<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>task.action_url&&window.open(task.action_url,"_blank","noopener,noreferrer")} className="rounded-2xl border border-white/10 bg-white/[.03] py-2.5 text-sm font-semibold">Join</button><button disabled={busy===task.id||task.completion_status==="approved"} onClick={()=>verify(task)} className="rounded-2xl bg-yellow-400 py-2.5 text-sm font-extrabold text-slate-950 disabled:opacity-50">{task.completion_status==="approved"?"Completed":busy===task.id?"Verifying...":"Verify"}</button></div>}</article>)}{!tasks.length&&<EmptyState title="No tasks yet" text="New tasks will appear here when available."/>}</div>}</Page>;
 else if(active==="Wallet")content=<Page title="MTN Services" icon={<Wallet size={20}/>}><div className="rounded-2xl bg-yellow-400 p-3.5 text-black"><p className="text-[10px] font-black uppercase tracking-[.18em]">MTN</p><h3 className="mt-1 text-xl font-black">Data & rewards</h3><p className="mt-1 text-sm">Manage your rewards, referrals and data redemption requests.</p></div><div className="mt-4 grid grid-cols-2 gap-3"><QuickAction icon={<CirclePlay size={18}/>} label="Rewards" sub="Earn data rewards" onClick={()=>setActive("Watch Ads")}/><QuickAction icon={<ClipboardList size={18}/>} label="Opportunities" sub="Available tasks" onClick={()=>setActive("Tasks")}/><QuickAction icon={<Users size={18}/>} label="Referral" sub={`${referralBalance>=1024?(referralBalance/1024).toFixed(2)+" GB":referralBalance.toLocaleString()+" MB"} available`} onClick={()=>setActive("Referral")}/><QuickAction icon={<Landmark size={18}/>} label="Redeem Data" sub="MTN data redemption" onClick={openWithdraw}/></div><button onClick={()=>setActive("History")} className="mt-4 flex w-full items-center justify-between rounded-2xl border border-white/10 bg-[#111111] px-4 py-3 text-sm font-bold text-white"><span>Transaction History</span><ChevronRight size={17}/></button></Page>;
 else if(active==="Referral")content=<Page title="Referral" icon={<Users size={20}/>}><div className="mb-4 rounded-2xl border border-yellow-300/20 bg-yellow-400/[.07] p-3"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-yellow-300">MTN referral program</p><h3 className="mt-1 text-lg font-bold">Invite friends to ViewCash</h3><p className="mt-1 text-sm leading-5 text-slate-400">Share your referral link and track your referral rewards here.</p></div><div className="mt-4 rounded-2xl border border-yellow-300/20 bg-yellow-400/[.06] p-3"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-yellow-600">Invite & earn</p><h3 className="mt-1 text-base font-bold">Your referral link</h3><p className="mt-2 break-all rounded-2xl bg-black/20 p-3 text-xs leading-5 text-slate-300">{referralLink||"Loading referral link..."}</p><p className="mt-2 text-[11px] text-slate-500">Code: {referralCode||"..."}</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={copyReferral} className="flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/[.03] py-2.5 text-sm font-semibold"><Copy size={16}/>Copy</button><button onClick={()=>{if(referralLink)window.open(`https://t.me/share/url?url=${encodeURIComponent(referralLink)}`,"_blank","noopener,noreferrer")}} className="flex items-center justify-center gap-2 rounded-2xl bg-yellow-400 py-2.5 text-sm font-extrabold text-slate-950"><Share2 size={16}/>Share</button></div></div></Page>;
 else if(active==="Withdraw")content=<Page title="Redeem Data" icon={<Wallet size={20}/>}><div className="rounded-2xl bg-yellow-400 p-3.5 text-black"><p className="text-[10px] font-black uppercase tracking-[.18em]">MTN</p><h3 className="mt-1 text-xl font-black">Redeem MTN Data</h3><p className="mt-1 text-sm">Enter your MTN data redemption details to continue.</p></div><button onClick={()=>window.location.assign("/withdraw")} className="mt-4 w-full rounded-2xl bg-yellow-400 py-3 text-sm font-extrabold text-slate-950">Open data redemption</button></Page>;
 else if(active==="History")content=<Page title="Activity" icon={<HistoryIcon size={20}/>}><div className="mb-4 rounded-2xl border border-white/10 bg-white/[.035] p-3"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Activity</p><h3 className="mt-1 text-base font-bold">Your recent activity</h3></div><button onClick={loadHistory} disabled={historyLoading} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">{historyLoading?"Loading...":"Refresh"}</button></div></div>{historyLoading&&history.length===0?<EmptyState title="Loading history" text="Fetching your latest activity..."/>:!history.length?<EmptyState icon={<HistoryIcon size={22}/>} title="No history yet" text="Your MTN rewards, opportunities, referrals and data redemptions will appear here."/>:<div className="space-y-2.5">{history.map(item=><article key={item.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-3.5"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${item.type==="data redemption"?"bg-rose-400/10 text-rose-300":item.type==="checkin"?"bg-amber-300/10 text-amber-300":"bg-yellow-400/10 text-yellow-300"}`}>{item.type==="checkin"?<CalendarCheck size={18}/>:item.type==="data redemption"?<Landmark size={18}/>:<Gift size={18}/>}</div><div className="min-w-0 flex-1"><p className="text-sm font-bold capitalize">{item.title}</p><p className="mt-0.5 truncate text-[11px] text-slate-500">{item.description}</p><p className="mt-1 text-[10px] text-slate-600">{new Date(item.created_at).toLocaleString()}</p></div><div className="text-right"><p className={`text-sm font-black ${item.amount<0?"text-rose-300":"text-yellow-300"}`}>{item.amount>0?"+":""}{item.amount.toLocaleString()}</p><p className="mt-0.5 text-[9px] font-bold uppercase tracking-wider text-slate-600">{item.status}</p></div></div></article>)}</div>}</Page>;
 else if(active==="Profile")content=<Page title="Profile" icon={<UserRound size={20}/>}><div className="rounded-2xl bg-yellow-400 p-3.5 text-black"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-black text-xl font-black text-yellow-400">MTN</div><div><p className="text-lg font-black">{displayName||"MTN User"}</p><p className="mt-1 text-xs font-semibold">Connected to ViewCash</p></div></div></div><div className="mt-4 space-y-2.5"><button onClick={()=>setActive("Wallet")} className="flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/[.035] px-4 py-3 text-sm font-semibold"><span>MTN Reward Wallet</span><ChevronRight size={17}/></button><button onClick={()=>setActive("Referral")} className="flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/[.035] px-4 py-3 text-sm font-semibold"><span>Referral Program</span><ChevronRight size={17}/></button><button onClick={()=>setActive("History")} className="flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/[.035] px-4 py-3 text-sm font-semibold"><span>Transaction History</span><ChevronRight size={17}/></button></div></Page>;
 else content=<section className="px-4 pt-4">{message&&<Notice text={message}/>}<div className="overflow-hidden rounded-xl bg-yellow-400 p-3 text-black"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em]">MTN</p><p className="mt-1 text-[1.4rem] leading-none font-black">{balance>=1024?(balance/1024).toFixed(2)+" GB":balance.toLocaleString()+" MB"}</p><p className="mt-1 text-[11px] font-semibold">Available MTN data</p></div><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-black text-[10px] font-black text-yellow-400">MTN</div></div></div><div id="mtn-services" className="mt-3 rounded-2xl border border-white/10 bg-white/[.025] p-3"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">MTN services</p><h3 className="mt-1 text-base font-bold">What do you want to do?</h3><div className="mt-3 grid grid-cols-2 gap-2"><QuickAction icon={<CalendarCheck size={18}/>} label="Daily Reward" sub={busy==="checkin"?"Processing...":"Claim reward"} onClick={checkIn} disabled={busy==="checkin"}/><QuickAction icon={<CirclePlay size={18}/>} label="Rewards" sub="Earn MTN data" onClick={()=>setActive("Watch Ads")}/><QuickAction icon={<ClipboardList size={18}/>} label="Opportunities" sub="Available tasks" onClick={()=>window.location.assign("/tasks")}/><QuickAction icon={<Users size={18}/>} label="Refer" sub={`${referralQualified}/${referralUnlockRequired} qualified`} onClick={()=>setActive("Referral")}/><QuickAction icon={<Wallet size={18}/>} label="Data Balance" sub={`${balance>=1024?(balance/1024).toFixed(2)+" GB":balance.toLocaleString()+" MB"} available`} onClick={()=>setActive("Wallet")}/><QuickAction icon={<HistoryIcon size={18}/>} label="History" sub="Transactions" onClick={()=>setActive("History")}/></div></div>{isAdmin&&<button onClick={()=>window.location.assign("/admin")} className="mt-4 w-full rounded-2xl border border-cyan-400/20 bg-yellow-400/10 py-3 text-sm font-bold text-yellow-300"><ShieldCheck size={18} className="inline mr-2"/>Admin Panel</button>}</section>;

 return <main className="mx-auto min-h-screen max-w-md bg-[#080808] pb-28 text-white shadow-2xl"><header className="bg-yellow-400 px-4 pb-5 pt-6 text-slate-950"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em]">MTN</p><h1 className="mt-1 text-xl font-black">ViewCash</h1><div className="mt-2 inline-flex items-center gap-2 rounded-full bg-black/10 px-2.5 py-1 text-[10px] font-bold"><span className="h-1.5 w-1.5 rounded-full bg-emerald-700"/>{status}</div></div><button onClick={()=>setActive("Profile")} className="flex h-11 w-11 items-center justify-center rounded-2xl bg-black text-sm font-black text-yellow-400">VC</button></div></header>{content}<nav className="fixed bottom-0 left-1/2 z-50 w-full max-w-md -translate-x-1/2 border-t border-white/10 bg-white/95 px-2 py-2 backdrop-blur-2xl"><div className="grid grid-cols-5 items-end gap-1">{nav.map(({label,icon:Icon})=>{const home=label==="Home",selected=active===label;return <button key={label} onClick={()=>label==="Tasks"?window.location.assign("/tasks"):setActive(label)} className={`relative flex min-h-10 flex-col items-center justify-center gap-1 rounded-2xl text-[9px] font-semibold ${home?"-mt-3":""} ${selected?"text-yellow-300":"text-slate-500"}`}><span className={home?`flex h-11 w-11 items-center justify-center rounded-full border-[4px] border-slate-50 ${selected?"bg-yellow-400 text-black":"bg-white/10 text-slate-300"}`:`flex h-8 w-8 items-center justify-center rounded-xl ${selected?"bg-yellow-400/10 text-yellow-300":"bg-white/[.025]"}`}><Icon size={home?22:17}/></span><span>{label}</span></button>})}</div></nav></main>;
}
function Page({title,icon,children}:{title:string;icon:ReactNode;children:ReactNode}){return <section className="px-4"><div className="mb-4 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl border border-cyan-300/15 bg-yellow-400/10 text-yellow-300">{icon}</div><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">ViewCash</p><h2 className="text-xl font-black">{title}</h2></div></div>{children}</section>}
function EmptyState({icon,title,text}:{icon?:ReactNode;title:string;text:string}){return <div className="rounded-3xl border border-white/10 bg-white/[.03] p-6 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[.05] text-yellow-300">{icon||<ClipboardList size={22}/>}</div><h3 className="mt-3 font-bold">{title}</h3><p className="mt-1 text-sm leading-5 text-slate-500">{text}</p></div>}
function Notice({text}:{text:string}){return <div className="mb-4 rounded-2xl border border-cyan-300/15 bg-yellow-400/[.08] p-3 text-xs leading-5 text-cyan-100">{text}</div>}
function QuickAction({icon,label,sub,onClick,disabled}:{icon:ReactNode;label:string;sub:string;onClick:()=>void;disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className="rounded-2xl border border-white/10 bg-white/[.035] p-3 text-left disabled:opacity-40"><div className="flex h-8 w-8 items-center justify-center rounded-xl bg-white/[.05] text-yellow-300">{icon}</div><p className="mt-2 text-[13px] font-bold">{label}</p><p className="mt-0.5 text-[10px] text-slate-500">{sub}</p></button>}
