"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";
import { CalendarCheck, ChevronRight, CirclePlay, ClipboardList, Copy, Gift, History as HistoryIcon, Home, Landmark, LockKeyhole, Megaphone, Share2, ShieldCheck, UserRound, Users, Wallet } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import MonetagWatch from "./components/monetag-watch";

type TelegramWebApp={initData:string;ready:()=>void;expand:()=>void};
declare global{interface Window{Telegram?:{WebApp?:TelegramWebApp};show_11801942?:((options?:Record<string,unknown>)=>Promise<unknown>)}}
type Section="Home"|"Watch Ads"|"Tasks"|"Wallet"|"Referral"|"Withdraw"|"History"|"Profile";
type WalletType="tasks"|"affiliate";
type Task={id:string;title:string;description:string|null;reward:number;task_type:string;action_url:string|null;verification_type:string;telegram_chat:string|null;completion_status?:string|null};
type HistoryItem={id:string;type:string;title:string;description:string;amount:number;balance_type:string;status:string;created_at:string};
const nav:{label:Section;icon:LucideIcon}[]=[{label:"Watch Ads",icon:CirclePlay},{label:"Tasks",icon:ClipboardList},{label:"Home",icon:Home},{label:"Referral",icon:Users},{label:"Profile",icon:UserRound}];

export default function HomePage(){
 const [active,setActive]=useState<Section>("Home"),[coins,setCoins]=useState(0),[referralCoins,setReferralCoins]=useState(0),[activated,setActivated]=useState(false),[isAdmin,setIsAdmin]=useState(false),[status,setStatus]=useState("Connecting..."),[displayName,setDisplayName]=useState(""),[initData,setInitData]=useState(""),[referralCode,setReferralCode]=useState(""),[referralLink,setReferralLink]=useState(""),[tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(false),[history,setHistory]=useState<HistoryItem[]>([]),[historyLoading,setHistoryLoading]=useState(false),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState(""),[email,setEmail]=useState(""),[showActivation,setShowActivation]=useState(false),[bankName,setBankName]=useState(""),[accountName,setAccountName]=useState(""),[accountNumber,setAccountNumber]=useState(""),[withdrawCoins,setWithdrawCoins]=useState(""),[withdrawWallet,setWithdrawWallet]=useState<WalletType>("tasks"),[resolvingAccount,setResolvingAccount]=useState(false);

 const refresh=useCallback(async(tg:TelegramWebApp)=>{const data=tg.initData?.trim();if(!data)throw new Error("Telegram session data is unavailable. Please reopen ViewCash from Telegram.");const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),12000);try{const r=await fetch("/api/telegram/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:data}),cache:"no-store",signal:controller.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Connection failed");setInitData(data);setCoins(Number(d.coins||0));setReferralCoins(Number(d.referral_coins||0));setActivated(Boolean(d.activated));setDisplayName(d.display_name||"Telegram User");setReferralCode(d.referral_code||"");setReferralLink(d.referral_link||"");setStatus(d.activated?"Account active":"Activation required");try{const a=await fetch("/api/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:data}),cache:"no-store"});setIsAdmin(a.ok)}catch{setIsAdmin(false)}}catch(e){if(e instanceof DOMException&&e.name==="AbortError")throw new Error("Connection timed out. Please reopen ViewCash.");throw e}finally{window.clearTimeout(timeout)}},[]);

 useEffect(()=>{let dead=false,timer:number|undefined,attempts=0;const run=async()=>{if(dead)return;const tg=window.Telegram?.WebApp;if(!tg){attempts++;if(attempts<40){timer=window.setTimeout(run,250);return}setStatus("Open ViewCash from Telegram");return}try{tg.ready();tg.expand();await refresh(tg)}catch(e){if(!dead)setStatus(e instanceof Error?e.message:"Unable to connect")}};const resume=()=>{attempts=0;run()};run();window.addEventListener("pageshow",resume);const onVisibility=()=>{if(document.visibilityState==="visible")resume()};document.addEventListener("visibilitychange",onVisibility);return()=>{dead=true;if(timer)window.clearTimeout(timer);window.removeEventListener("pageshow",resume);document.removeEventListener("visibilitychange",onVisibility)}},[refresh]);

 useEffect(()=>{if(active!=="Withdraw"){setResolvingAccount(false);return}const number=accountNumber.trim();const bank=bankName.trim();if(!/^\d{10}$/.test(number)||!bank){setAccountName("");setResolvingAccount(false);return}let cancelled=false;setResolvingAccount(true);setMessage("");const timer=window.setTimeout(async()=>{try{const r=await fetch("/api/withdrawals/resolve-account",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bank_name:bank,account_number:number}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(cancelled)return;if(!r.ok)throw new Error(d.error||"Account could not be verified");setAccountName(String(d.account_name||""));setBankName(String(d.bank_name||bank))}catch(e){if(!cancelled){setAccountName("");setMessage(e instanceof Error?e.message:"Account could not be verified")}}finally{if(!cancelled)setResolvingAccount(false)}},450);return()=>{cancelled=true;window.clearTimeout(timer)}},[active,accountNumber,bankName]);

 const checkIn=async()=>{if(!initData)return setMessage("Open ViewCash from Telegram first.");setBusy("checkin");setMessage("");let session:{session_id:string;request_var:string;ymid:string}|null=null;try{const start=await fetch("/api/checkin-ad/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData}),cache:"no-store"});const s=await start.json().catch(()=>({}));if(!start.ok)throw new Error(s.error==="ALREADY_CHECKED_IN"?`Already checked in today. Streak: day ${Number(s.streak_day||1)}.`:(s.error||"Unable to start check-in ad."));session={session_id:String(s.session_id),request_var:String(s.request_var),ymid:String(s.ymid)};const zone="11801942";if(typeof window.show_11801942!=="function"){const existing=document.querySelector(`script[data-viewcash-checkin-ad="${zone}"]`);if(!existing){const script=document.createElement("script");script.src="https://libtl.com/sdk.js";script.async=true;script.dataset.zone=zone;script.dataset.sdk=`show_${zone}`;script.dataset.viewcashCheckinAd=zone;document.head.appendChild(script)}const readyAt=Date.now();while(typeof window.show_11801942!=="function"&&Date.now()-readyAt<12000)await new Promise(r=>window.setTimeout(r,250))}const show=window.show_11801942;if(!show)throw new Error("Check-in video is not ready yet. Please try again.");setMessage("Watch the full video to complete your daily check-in.");await show({type:"end",ymid:session.ymid,requestVar:session.request_var,catchIfNoFeed:true});const complete=await fetch("/api/checkin-ad/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,session_id:session.session_id,request_var:session.request_var,ymid:session.ymid}),cache:"no-store"});const d=await complete.json().catch(()=>({}));if(!complete.ok||!d?.ok){const error=String(d?.error||"CHECKIN_CREDIT_FAILED");if(error==="VIEW_TOO_SHORT")throw new Error("The video was not completed. Please watch the full video.");throw new Error(error==="ALREADY_CHECKED_IN"?`Already checked in today. Streak: day ${Number(d.streak_day||1)}.`:(d?.message||"Check-in could not be credited."))}setCoins(v=>v+Number(d.reward_coins||0));setMessage(Number(d.reward_coins||0)>0?`Daily check-in claimed: +${Number(d.reward_coins).toLocaleString()} coins. Streak: day ${Number(d.streak_day||1)}.`:`Daily check-in already completed. Streak: day ${Number(d.streak_day||1)}.`);if(Number(d.reward_coins||0)>0)loadHistory()}catch(e){setMessage(e instanceof Error?e.message:"Check-in failed")}finally{setBusy(null)}};
 const loadTasks=useCallback(async()=>{if(!initData)return;setLoading(true);try{const r=await fetch(`/api/tasks?initData=${encodeURIComponent(initData)}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to load tasks");setTasks(d.tasks||[])}catch(e){setMessage(e instanceof Error?e.message:"Unable to load tasks")}finally{setLoading(false)}},[initData]);
 const loadHistory=useCallback(async()=>{if(!initData)return;setHistoryLoading(true);try{const r=await fetch("/api/history",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to load history");setHistory(Array.isArray(d.history)?d.history:[])}catch(e){setMessage(e instanceof Error?e.message:"Unable to load history")}finally{setHistoryLoading(false)}},[initData]);
 useEffect(()=>{if(active==="Tasks"&&activated)loadTasks()},[active,activated,loadTasks]);
 useEffect(()=>{if(active==="History")loadHistory()},[active,loadHistory]);
 const verify=async(task:Task)=>{setBusy(task.id);setMessage("");try{const r=await fetch("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task_id:task.id,initData}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Task verification failed");setCoins(v=>v+Number(d.reward||0));setMessage(`Task completed: +${Number(d.reward||0).toLocaleString()} coins`);await loadTasks();loadHistory()}catch(e){setMessage(e instanceof Error?e.message:"Task verification failed")}finally{setBusy(null)}};
 const openWithdraw=(wallet:WalletType)=>{window.location.assign(`/withdraw?wallet=${wallet}`)};
 const withdraw=async()=>{const amount=Number(withdrawCoins),available=withdrawWallet==="affiliate"?referralCoins:coins;if(!activated)return setMessage("Activate your account first.");if(!Number.isInteger(amount)||amount<=0)return setMessage("Enter a valid coin amount.");if(amount>available)return setMessage(`Insufficient ${withdrawWallet==="affiliate"?"affiliate":"task"} coins.`);if(!bankName||!accountName||!/^[0-9]{10}$/.test(accountNumber))return setMessage("Enter a valid bank and account number so the account name can be verified automatically.");setBusy("withdraw");try{const r=await fetch("/api/withdrawals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,bank_name:bankName,account_name:accountName,account_number:accountNumber,coins:amount,wallet_type:withdrawWallet}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Withdrawal failed");if(withdrawWallet==="affiliate")setReferralCoins(v=>v-amount);else setCoins(v=>v-amount);setWithdrawCoins("");setMessage(`${withdrawWallet==="affiliate"?"Affiliate":"Task"} wallet withdrawal submitted. Cash value: ₦${Number(d.cash_amount||0).toFixed(2)}`);loadHistory()}catch(e){setMessage(e instanceof Error?e.message:"Withdrawal failed")}finally{setBusy(null)}};
 const copyReferral=async()=>{if(!referralLink)return;try{await navigator.clipboard.writeText(referralLink);setMessage("Referral link copied.")}catch{setMessage("Copy failed. Long-press the link to copy it.")}};
 const activate=async()=>{setMessage("");if(!email)return setShowActivation(true);setBusy("activate");try{const r=await fetch("/api/account/activate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,email}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to start activation payment.");if(!d.payment_url)throw new Error("Payment link was not created.");window.location.assign(d.payment_url)}catch(e){setMessage(e instanceof Error?e.message:"Unable to start activation payment.");setBusy(null)}};

 const locked=["Watch Ads","Tasks","Withdraw"].includes(active)&&!activated;
 const activationBox=!activated?<div className="mb-4 overflow-hidden rounded-3xl border border-amber-300/20 bg-gradient-to-br from-amber-300/[.10] via-white/[.035] to-transparent p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-amber-300/10 text-amber-300"><Landmark size={19}/></span><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-amber-300">Get started</p><h2 className="mt-1 text-base font-bold">Activate your account</h2><p className="mt-1 text-xs leading-5 text-slate-400">Unlock ads, tasks and withdrawals after secure activation.</p></div></div>{showActivation&&<input value={email} onChange={e=>setEmail(e.target.value)} className="field mt-3" placeholder="Email for payment receipt" type="email" autoComplete="email"/>}<button onClick={()=>showActivation?activate():setShowActivation(true)} disabled={busy==="activate"} className="mt-3 w-full rounded-2xl bg-cyan-400 py-3 text-sm font-extrabold text-slate-950 disabled:opacity-50">{busy==="activate"?"Opening payment...":showActivation?"Continue to Payment":"Activate Account"}</button></div>:null;

 let content:ReactNode;
 if(locked)content=<Page title={active} icon={<LockKeyhole size={20}/>}><EmptyState icon={<LockKeyhole size={28}/>} title="Locked until activation" text="Complete account activation to unlock this section."/></Page>;
 else if(active==="Watch Ads")content=<Page title="Watch Ads" icon={<CirclePlay size={20}/>}><div className="mb-4 rounded-3xl border border-cyan-300/15 bg-cyan-400/[.06] p-4"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-300">Rewarded ads</p><h3 className="mt-1 text-lg font-bold">Turn attention into coins</h3><p className="mt-1 text-sm leading-5 text-slate-400">Watch a valid rewarded ad. Coins are added only after server confirmation.</p></div><MonetagWatch initData={initData}/></Page>;
 else if(active==="Tasks")content=<Page title="Tasks" icon={<ClipboardList size={20}/>} >{loading?<EmptyState title="Loading tasks" text="Finding available tasks for your account..."/>:<div className="space-y-3">{tasks.map(task=><article key={task.id} className="rounded-3xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-slate-500">Task</p><h3 className="mt-1 text-base font-bold">{task.title}</h3><p className="mt-1.5 text-sm leading-5 text-slate-400">{task.description||"Complete this task to earn coins."}</p></div><span className="shrink-0 rounded-full bg-cyan-400/10 px-2.5 py-1.5 text-[11px] font-bold text-cyan-300">+{Number(task.reward).toLocaleString()}</span></div>{task.verification_type==="telegram"&&<div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>task.action_url&&window.open(task.action_url,"_blank","noopener,noreferrer")} className="rounded-2xl border border-white/10 bg-white/[.03] py-2.5 text-sm font-semibold">Join</button><button disabled={busy===task.id||task.completion_status==="approved"} onClick={()=>verify(task)} className="rounded-2xl bg-cyan-400 py-2.5 text-sm font-extrabold text-slate-950 disabled:opacity-50">{task.completion_status==="approved"?"Completed":busy===task.id?"Verifying...":"Verify"}</button></div>}</article>)}{!tasks.length&&<EmptyState title="No tasks yet" text="New tasks will appear here when available."/>}</div>}</Page>;
 else if(active==="Wallet")content=<Page title="Wallet" icon={<Wallet size={20}/>}><div className="space-y-3"><WalletBox title="Task Wallet" subtitle="Ads and task rewards" coins={coins} onWithdraw={()=>openWithdraw("tasks")}/><WalletBox title="Affiliate Wallet" subtitle="Referral rewards" coins={referralCoins} onWithdraw={()=>openWithdraw("affiliate")}/></div><button onClick={()=>setActive("History")} className="mt-4 flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/[.035] px-4 py-3 text-sm font-bold"><span className="flex items-center gap-2"><HistoryIcon size={17} className="text-cyan-300"/>Transaction History</span><ChevronRight size={17}/></button><div className="mt-4 rounded-2xl border border-white/10 bg-white/[.025] p-3 text-xs leading-5 text-slate-500">Your Task and Affiliate wallets are separate balances.</div></Page>;
 else if(active==="Referral")content=<Page title="Referral" icon={<Users size={20}/>}><WalletBox title="Affiliate Wallet" subtitle="Referral rewards" coins={referralCoins} onWithdraw={()=>openWithdraw("affiliate")}/><div className="mt-4 rounded-3xl border border-cyan-300/15 bg-cyan-400/[.05] p-4"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-300">Invite & earn</p><h3 className="mt-1 text-base font-bold">Your referral link</h3><p className="mt-2 break-all rounded-2xl bg-black/20 p-3 text-xs leading-5 text-slate-300">{referralLink||"Loading referral link..."}</p><p className="mt-2 text-[11px] text-slate-500">Code: {referralCode||"..."}</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={copyReferral} className="flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/[.03] py-2.5 text-sm font-semibold"><Copy size={16}/>Copy</button><button onClick={()=>{if(referralLink)window.open(`https://t.me/share/url?url=${encodeURIComponent(referralLink)}`,"_blank","noopener,noreferrer")}} className="flex items-center justify-center gap-2 rounded-2xl bg-cyan-400 py-2.5 text-sm font-extrabold text-slate-950"><Share2 size={16}/>Share</button></div></div></Page>;
 else if(active==="Withdraw")content=<Page title="Withdraw" icon={<Landmark size={20}/>}><div className="rounded-3xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Choose wallet</p><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setWithdrawWallet("tasks")} className={`rounded-2xl border py-3 text-xs font-bold ${withdrawWallet==="tasks"?"border-cyan-300/40 bg-cyan-400/10 text-cyan-300":"border-white/10 bg-white/[.03] text-slate-400"}`}>Task Wallet</button><button type="button" onClick={()=>setWithdrawWallet("affiliate")} className={`rounded-2xl border py-3 text-xs font-bold ${withdrawWallet==="affiliate"?"border-cyan-300/40 bg-cyan-400/10 text-cyan-300":"border-white/10 bg-white/[.03] text-slate-400"}`}>Affiliate Wallet</button></div></div><div className="mt-3"><WalletBox title={withdrawWallet==="affiliate"?"Affiliate Wallet":"Task Wallet"} subtitle={withdrawWallet==="affiliate"?"Referral coins":"Task and ad coins"} coins={withdrawWallet==="affiliate"?referralCoins:coins}/></div><div className="mt-4 space-y-3"><input value={bankName} onChange={e=>setBankName(e.target.value)} className="field" placeholder="Bank name" autoComplete="off"/><input value={accountNumber} onChange={e=>setAccountNumber(e.target.value.replace(/\D/g,"").slice(0,10))} className="field" placeholder="Account number" inputMode="numeric" autoComplete="off"/><div className="field flex items-center justify-between gap-3"><span className={accountName?"text-slate-100":"text-slate-500"}>{resolvingAccount?"Verifying account name...":accountName||"Account name will appear automatically"}</span>{accountName&&<span className="text-[10px] font-bold uppercase tracking-wider text-emerald-400">Verified</span>}</div><input value={withdrawCoins} onChange={e=>setWithdrawCoins(e.target.value.replace(/\D/g,""))} className="field" placeholder={`${withdrawWallet==="affiliate"?"Affiliate":"Task"} coins to withdraw`} inputMode="numeric"/><button disabled={busy==="withdraw"||resolvingAccount||!accountName} onClick={withdraw} className="w-full rounded-2xl bg-cyan-400 py-3 text-sm font-extrabold text-slate-950 disabled:opacity-50">{busy==="withdraw"?"Submitting...":resolvingAccount?"Verifying account...":"Submit withdrawal"}</button></div></Page>;
 else if(active==="History")content=<Page title="History" icon={<HistoryIcon size={20}/>}><div className="mb-4 rounded-3xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Activity</p><h3 className="mt-1 text-base font-bold">Your recent activity</h3></div><button onClick={loadHistory} disabled={historyLoading} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">{historyLoading?"Loading...":"Refresh"}</button></div></div>{historyLoading&&history.length===0?<EmptyState title="Loading history" text="Fetching your latest activity..."/>:!history.length?<EmptyState icon={<HistoryIcon size={22}/>} title="No history yet" text="Your check-ins, ad rewards, task rewards and withdrawals will appear here."/>:<div className="space-y-2.5">{history.map(item=><article key={item.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-3.5"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${item.type==="withdrawal"?"bg-rose-400/10 text-rose-300":item.type==="checkin"?"bg-amber-300/10 text-amber-300":"bg-cyan-400/10 text-cyan-300"}`}>{item.type==="checkin"?<CalendarCheck size={18}/>:item.type==="withdrawal"?<Landmark size={18}/>:<Gift size={18}/>}</div><div className="min-w-0 flex-1"><p className="text-sm font-bold capitalize">{item.title}</p><p className="mt-0.5 truncate text-[11px] text-slate-500">{item.description}</p><p className="mt-1 text-[10px] text-slate-600">{new Date(item.created_at).toLocaleString()}</p></div><div className="text-right"><p className={`text-sm font-black ${item.amount<0?"text-rose-300":"text-cyan-300"}`}>{item.amount>0?"+":""}{item.amount.toLocaleString()}</p><p className="mt-0.5 text-[9px] font-bold uppercase tracking-wider text-slate-600">{item.status}</p></div></div></article>)}</div>}</Page>;
 else if(active==="Profile")content=<Page title="Profile" icon={<UserRound size={20}/>}><div className="rounded-3xl border border-white/10 bg-cyan-400/[.06] p-5"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-400 text-xl font-black text-slate-950">VC</div><div><p className="text-lg font-bold">{displayName||"Telegram User"}</p><p className="mt-1 text-xs text-slate-500">{activated?"Account active":"Activation required"}</p></div></div></div></Page>;
 else content=<section className="px-4">{activationBox}{message&&<Notice text={message}/>}<div className="rounded-[1.6rem] border border-cyan-300/20 bg-cyan-400/[.10] p-5"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-200/80">Total balance</p><p className="mt-2 text-4xl font-black">{coins.toLocaleString()} <span className="text-sm text-cyan-200">coins</span></p><p className="mt-2 text-xs text-slate-400">Task wallet balance</p><button onClick={()=>setActive("Wallet")} className="mt-5 flex w-full items-center justify-between rounded-2xl bg-white/[.07] px-4 py-3 text-sm font-semibold"><span>Manage wallets</span><ChevronRight size={17}/></button></div><div className="mt-3 grid grid-cols-2 gap-3"><MiniStat label="Affiliate" value={referralCoins.toLocaleString()} icon={<Users size={16}/>}/><MiniStat label="Status" value={activated?"Active":"Locked"} icon={activated?<ShieldCheck size={16}/>:<LockKeyhole size={16}/>}/></div><div className="mt-5 grid grid-cols-2 gap-2.5"><QuickAction icon={<CalendarCheck size={18}/>} label="Daily Check-in" sub={busy==="checkin"?"Watching ad...":"Watch ad & claim"} onClick={checkIn} disabled={busy==="checkin"}/><QuickAction icon={<CirclePlay size={18}/>} label="Watch Ads" sub="Earn coins" onClick={()=>setActive("Watch Ads")} disabled={!activated}/><QuickAction icon={<ClipboardList size={18}/>} label="Tasks" sub="Complete tasks" onClick={()=>window.location.assign("/tasks")} disabled={!activated}/><QuickAction icon={<Users size={18}/>} label="Referral" sub="Invite friends" onClick={()=>setActive("Referral")}/><QuickAction icon={<Wallet size={18}/>} label="Wallet" sub="Manage balance" onClick={()=>setActive("Wallet")}/><QuickAction icon={<HistoryIcon size={18}/>} label="History" sub="View activity" onClick={()=>setActive("History")}/>{isAdmin&&<QuickAction icon={<Megaphone size={18}/>} label="Advert" sub="Coming Soon" onClick={()=>window.location.assign("/advert")}/>}</div>{isAdmin&&<button onClick={()=>window.location.assign("/admin")} className="mt-4 w-full rounded-2xl border border-cyan-400/20 bg-cyan-400/10 py-3 text-sm font-bold text-cyan-300"><ShieldCheck size={18} className="inline mr-2"/>Admin Panel</button>}</section>;

 return <main className="mx-auto min-h-screen max-w-md bg-[#070b14] pb-28 shadow-2xl"><header className="px-4 pb-4 pt-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">Welcome back</p><h1 className="mt-1 text-2xl font-black">View<span className="text-cyan-400">Cash</span></h1><div className="mt-2 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-2.5 py-1 text-[10px] font-semibold text-slate-400"><span className={`h-1.5 w-1.5 rounded-full ${status==="Account active"?"bg-emerald-400":"bg-amber-300"}`}/>{status}</div></div><button onClick={()=>setActive("Profile")} className="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white/[.05] text-sm font-black text-cyan-300">VC</button></div></header>{content}<nav className="fixed bottom-0 left-1/2 z-50 w-full max-w-md -translate-x-1/2 border-t border-white/10 bg-[#080c16]/95 px-2 py-2 backdrop-blur-2xl"><div className="grid grid-cols-5 items-end gap-1">{nav.map(({label,icon:Icon})=>{const home=label==="Home",selected=active===label;return <button key={label} onClick={()=>label==="Tasks"?window.location.assign("/tasks"):setActive(label)} className={`relative flex min-h-12 flex-col items-center justify-center gap-1 rounded-2xl text-[9px] font-semibold ${home?"-mt-6":""} ${selected?"text-cyan-300":"text-slate-500"}`}><span className={home?`flex h-14 w-14 items-center justify-center rounded-full border-[5px] border-[#070b14] ${selected?"bg-cyan-400 text-slate-950":"bg-white/10 text-slate-300"}`:`flex h-8 w-8 items-center justify-center rounded-xl ${selected?"bg-cyan-400/10 text-cyan-300":"bg-white/[.025]"}`}><Icon size={home?22:17}/></span><span>{label}</span></button>})}</div></nav></main>;
}
function Page({title,icon,children}:{title:string;icon:ReactNode;children:ReactNode}){return <section className="px-4"><div className="mb-4 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl border border-cyan-300/15 bg-cyan-400/10 text-cyan-300">{icon}</div><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">ViewCash</p><h2 className="text-xl font-black">{title}</h2></div></div>{children}</section>}
function EmptyState({icon,title,text}:{icon?:ReactNode;title:string;text:string}){return <div className="rounded-3xl border border-white/10 bg-white/[.03] p-6 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[.05] text-cyan-300">{icon||<ClipboardList size={22}/>}</div><h3 className="mt-3 font-bold">{title}</h3><p className="mt-1 text-sm leading-5 text-slate-500">{text}</p></div>}
function Notice({text}:{text:string}){return <div className="mb-4 rounded-2xl border border-cyan-300/15 bg-cyan-400/[.06] p-3 text-xs leading-5 text-cyan-100">{text}</div>}
function MiniStat({label,value,icon}:{label:string;value:string;icon:ReactNode}){return <div className="rounded-3xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-center gap-2 text-cyan-300">{icon}<span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</span></div><p className="mt-2 text-lg font-black">{value}</p></div>}
function WalletBox({title,subtitle,coins,onWithdraw}:{title:string;subtitle:string;coins:number;onWithdraw?:()=>void}){return <div className="rounded-3xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><p className="text-xl font-black">{coins.toLocaleString()}</p></div>{onWithdraw&&<button onClick={onWithdraw} className="mt-3 flex w-full items-center justify-center rounded-2xl bg-cyan-400 py-2.5 text-sm font-extrabold text-slate-950">Withdraw</button>}</div>}
function QuickAction({icon,label,sub,onClick,disabled}:{icon:ReactNode;label:string;sub:string;onClick:()=>void;disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className="rounded-3xl border border-white/10 bg-white/[.035] p-4 text-left disabled:opacity-40"><div className="flex h-9 w-9 items-center justify-center rounded-2xl bg-white/[.05] text-cyan-300">{icon}</div><p className="mt-3 text-sm font-bold">{label}</p><p className="mt-1 text-[11px] text-slate-500">{sub}</p></button>}
