"use client";
import { useEffect, useState } from "react";

type Task={id:string;title:string;description:string|null;reward:number;task_type:string;action_url:string|null;daily_limit:number|null;completion_limit:number|null;completed_count:number;status:string};
type Draft={title:string;description:string;reward:string;task_type:string;action_url:string;daily_limit:string;completion_limit:string};
type Submission={id:string;task_id:string;user_id:string;proof_url:string|null;status:string;created_at:string;reviewed_at:string|null;users:{telegram_id:number;username:string|null;first_name:string|null;last_name:string|null}|null;tasks:{title:string;reward:number}|null};
const emptyDraft:Draft={title:"",description:"",reward:"0",task_type:"manual",action_url:"",daily_limit:"",completion_limit:""};
function proofIsImage(value:string|null){return !!value && (/^data:image\/(jpeg|jpg|png|webp);base64,/i.test(value)||/^https?:\/\//i.test(value));}

export default function AdminTasks(){
 const [authorized,setAuthorized]=useState(false),[message,setMessage]=useState("Checking admin access..."),[tasks,setTasks]=useState<Task[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState<Draft>(emptyDraft),[saving,setSaving]=useState(false),[reviewing,setReviewing]=useState<string|null>(null),[notice,setNotice]=useState("");
 useEffect(()=>{(async()=>{try{const tg=window.Telegram?.WebApp;if(!tg?.initData){setMessage("Open the Admin Panel from Telegram.");return}tg.ready?.();tg.expand?.();const r=await fetch("/api/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:tg.initData}),cache:"no-store"});if(!r.ok){setMessage((await r.json().catch(()=>({}))).error||"Admin access denied.");return}setAuthorized(true);await Promise.all([loadTasks(),loadSubmissions()])}catch{setMessage("Unable to verify admin access.")}})()},[]);
 const loadTasks=async()=>{const r=await fetch("/api/admin/tasks",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setTasks(d.tasks||[]);else setNotice(d.error||"Unable to load tasks.")};
 const loadSubmissions=async()=>{const r=await fetch("/api/admin/task-submissions?status=pending",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setSubmissions(d.submissions||[]);else setNotice(d.error||"Unable to load task proofs.")};
 const beginEdit=(t:Task)=>{setEditing(t.id);setNotice("");setDraft({title:t.title||"",description:t.description||"",reward:String(t.reward??0),task_type:t.task_type||"manual",action_url:t.action_url||"",daily_limit:t.daily_limit==null?"":String(t.daily_limit),completion_limit:t.completion_limit==null?"":String(t.completion_limit)})};
 const create=async()=>{setSaving(true);setNotice("");try{const r=await fetch("/api/admin/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,reward:Number(draft.reward),status:"active"})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to create task");setDraft(emptyDraft);setNotice("Task created successfully.");await loadTasks()}catch(e){setNotice(e instanceof Error?e.message:"Unable to create task")}finally{setSaving(false)}};
 const save=async()=>{if(!editing)return;setSaving(true);setNotice("");try{const r=await fetch("/api/admin/tasks",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:editing,...draft,reward:Number(draft.reward),daily_limit:draft.daily_limit,completion_limit:draft.completion_limit})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to save task");setEditing(null);setNotice("Task updated successfully.");await loadTasks()}catch(e){setNotice(e instanceof Error?e.message:"Unable to save task")}finally{setSaving(false)}};
 const toggle=async(t:Task)=>{const r=await fetch("/api/admin/tasks",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:t.id,status:t.status==="active"?"inactive":"active"})});if(r.ok)await loadTasks()};
 const remove=async(t:Task)=>{if(!window.confirm(`Delete task "${t.title}"?`))return;const r=await fetch(`/api/admin/tasks?id=${encodeURIComponent(t.id)}`,{method:"DELETE"});if(r.ok)await loadTasks()};
 const review=async(id:string,action:"approve"|"reject")=>{if(reviewing)return;setReviewing(id);setNotice("");try{const r=await fetch("/api/admin/task-submissions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to review proof");setNotice(action==="approve"?"Task proof approved and reward credited.":"Task proof rejected.");await Promise.all([loadSubmissions(),loadTasks()])}catch(e){setNotice(e instanceof Error?e.message:"Unable to review proof")}finally{setReviewing(null)}};
 if(!authorized)return <main className="flex min-h-screen items-center justify-center bg-[#080d18] px-6 text-center text-white"><div><h1 className="text-3xl font-extrabold">View<span className="text-cyan-400">Cash</span></h1><p className="mt-3 text-slate-400">{message}</p></div></main>;
 const form=<div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-lg font-bold">{editing?"Edit Task":"Create Task"}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className="text-sm text-slate-400">Title</span><input className="field mt-2" value={draft.title} onChange={e=>setDraft(x=>({...x,title:e.target.value}))}/></label><label><span className="text-sm text-slate-400">Reward</span><input className="field mt-2" type="number" min="0" value={draft.reward} onChange={e=>setDraft(x=>({...x,reward:e.target.value}))}/></label><label><span className="text-sm text-slate-400">Action URL</span><input className="field mt-2" value={draft.action_url} onChange={e=>setDraft(x=>({...x,action_url:e.target.value}))}/></label><label><span className="text-sm text-slate-400">Task type</span><select className="field mt-2" value={draft.task_type} onChange={e=>setDraft(x=>({...x,task_type:e.target.value}))}><option value="manual">Manual</option><option value="link">Link</option><option value="social">Social</option><option value="telegram">Telegram</option></select></label><label><span className="text-sm text-slate-400">Daily limit</span><input className="field mt-2" type="number" min="1" value={draft.daily_limit} onChange={e=>setDraft(x=>({...x,daily_limit:e.target.value}))}/></label><label><span className="text-sm text-slate-400">Completion limit</span><input className="field mt-2" type="number" min="1" value={draft.completion_limit} onChange={e=>setDraft(x=>({...x,completion_limit:e.target.value}))}/></label></div><textarea className="field mt-3 min-h-24" placeholder="Description" value={draft.description} onChange={e=>setDraft(x=>({...x,description:e.target.value}))}/><div className="mt-4 flex gap-2"><button disabled={saving} onClick={editing?save:create} className="rounded-xl bg-cyan-400 px-5 py-2.5 text-sm font-extrabold text-slate-950">{saving?"Saving...":editing?"Save Changes":"Create Task"}</button>{editing&&<button onClick={()=>{setEditing(null);setDraft(emptyDraft)}} className="rounded-xl border border-white/10 px-5 py-2.5 text-sm font-bold">Cancel</button>}</div></div>;
 return <main className="min-h-screen bg-[#080d18] text-white"><section className="mx-auto max-w-5xl p-5 md:p-8"><div className="mb-6 flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-slate-500">ViewCash Admin</p><h1 className="mt-1 text-3xl font-extrabold">Task Management</h1><p className="mt-1 text-sm text-slate-400">Create, edit, enable, disable or delete worker tasks.</p></div><button onClick={()=>window.location.href="/admin"} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold">Back</button></div>{notice&&<div className="mb-4 rounded-2xl border border-cyan-300/15 bg-cyan-400/[.06] p-3 text-sm text-cyan-100">{notice}</div>}
 <section className="mb-6 rounded-3xl border border-amber-300/15 bg-amber-400/[.04] p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-extrabold">Task Proof Review</h2><p className="mt-1 text-sm text-slate-400">Pending worker screenshots appear here. Approve only after checking the proof.</p></div><span className="rounded-full bg-amber-400/15 px-3 py-1 text-xs font-extrabold text-amber-200">{submissions.length} pending</span></div><div className="mt-4 space-y-4">{submissions.map(s=>{const u=s.users;const t=s.tasks;const name=[u?.first_name,u?.last_name].filter(Boolean).join(" ")||u?.username||`Telegram ${u?.telegram_id||"user"}`;const proof=s.proof_url;return <article key={s.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="grid gap-4 md:grid-cols-[220px_1fr]"><div className="overflow-hidden rounded-2xl border border-white/10 bg-black/30">{proofIsImage(proof)?<img src={proof!} alt="Worker task proof" className="h-56 w-full object-contain" referrerPolicy="no-referrer"/>:<div className="flex h-56 items-center justify-center px-4 text-center text-xs text-slate-500">No screenshot available</div>}</div><div><p className="text-lg font-extrabold">{t?.title||"Task"}</p><p className="mt-1 text-sm text-slate-400">Worker: {name}</p><p className="mt-1 text-xs text-slate-500">Telegram ID: {u?.telegram_id||"—"} · Reward: {t?.reward??0} · Submitted: {new Date(s.created_at).toLocaleString()}</p><div className="mt-5 flex gap-2"><button disabled={reviewing===s.id} onClick={()=>review(s.id,"approve")} className="rounded-xl bg-emerald-400 px-5 py-2.5 text-sm font-extrabold text-slate-950">{reviewing===s.id?"Processing...":"Approve"}</button><button disabled={reviewing===s.id} onClick={()=>review(s.id,"reject")} className="rounded-xl border border-red-400/25 bg-red-400/5 px-5 py-2.5 text-sm font-extrabold text-red-200">Reject</button></div></div></div></article>})}{submissions.length===0&&<div className="rounded-2xl border border-dashed border-white/10 p-7 text-center text-sm text-slate-500">No pending task proofs.</div>}</div></section>
 {!editing&&form}<div className="mt-5 space-y-3">{tasks.map(t=>editing===t.id?form:<div key={t.id} className="rounded-3xl border border-white/10 bg-white/[.035] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{t.title}</p><p className="mt-1 text-xs text-slate-500">Reward: {t.reward} · Completed: {t.completed_count||0} · {t.task_type} · {t.status}</p>{t.action_url&&<p className="mt-1 truncate text-xs text-slate-600">{t.action_url}</p>}</div><div className="flex gap-2"><button onClick={()=>beginEdit(t)} className="rounded-xl bg-cyan-400 px-4 py-2 text-xs font-extrabold text-slate-950">Edit</button><button onClick={()=>toggle(t)} className="rounded-xl border border-white/10 px-4 py-2 text-xs font-bold">{t.status==="active"?"Disable":"Enable"}</button><button onClick={()=>remove(t)} className="rounded-xl border border-red-400/20 px-4 py-2 text-xs font-bold text-red-300">Delete</button></div></div></div>)}{tasks.length===0&&<div className="rounded-3xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No tasks found.</div>}</div></section></main>;
}
