"use client";

import { useEffect, useState } from "react";

type TelegramWebApp = { initData: string; ready: () => void; expand: () => void };
declare global { interface Window { Telegram?: { WebApp?: TelegramWebApp } } }
type Withdrawal = { id:string; amount:number; bank_name:string; account_name:string; account_number:string; status:string; admin_note:string|null; created_at:string; processed_at:string|null; users?:{username?:string;first_name?:string;last_name?:string}|null };

export default function WithdrawalsPage(){
 const [authorized,setAuthorized]=useState(false),[message,setMessage]=useState("Checking admin access..."),[status,setStatus]=useState("pending"),[rows,setRows]=useState<Withdrawal[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState("");
 useEffect(()=>{(async()=>{const w=window.Telegram?.WebApp;if(!w?.initData){setMessage("Open this page from Telegram.");return}w.ready();w.expand();const r=await fetch("/api/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:w.initData}),cache:"no-store"});if(!r.ok){setMessage("Admin access denied.");return}setAuthorized(true)})().catch(()=>setMessage("Unable to verify admin access."))},[]);
 const load=async()=>{setError("");const r=await fetch(`/api/admin/withdrawals?status=${status}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setRows(d.withdrawals||[]);else setError("Unable to load withdrawals.")};
 useEffect(()=>{if(authorized)load()},[authorized,status]);
 const update=async(id:string,next:string)=>{setBusy(id);setError("");const r=await fetch("/api/admin/withdrawals",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:next,admin_note:notes[id]||null})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||"Unable to update withdrawal");else await load();setBusy(null)};
 if(!authorized)return <main className="flex min-h-screen items-center justify-center bg-[#080d18] px-6 text-center text-white"><div><h1 className="text-3xl font-extrabold">View<span className="text-cyan-400">Cash</span></h1><p className="mt-3 text-slate-400">{message}</p></div></main>;
 return <main className="min-h-screen bg-[#080d18] p-5 text-white"><div className="mx-auto max-w-2xl"><div className="mb-6 flex items-start gap-3"><button type="button" onClick={()=>window.location.href="/admin"} className="mt-1 shrink-0 rounded-xl border border-white/10 bg-white/[.035] px-3 py-2 text-sm font-semibold text-slate-300 hover:bg-white/10">← Back</button><div><h1 className="text-2xl font-extrabold">Withdrawals</h1><p className="mt-1 text-sm text-slate-500">Review and process user withdrawal requests.</p></div></div><div className="mb-5 flex gap-2 overflow-x-auto">{["pending","approved","paid","rejected","cancelled"].map(s=><button key={s} onClick={()=>setStatus(s)} className={`shrink-0 rounded-xl px-4 py-2 text-xs font-semibold ${status===s?"bg-cyan-400/10 text-cyan-300":"border border-white/10 text-slate-400"}`}>{s}</button>)}</div>{error&&<p className="mb-4 text-sm text-red-300">{error}</p>}<div className="space-y-4">{rows.map(w=>{const u=w.users;return <div key={w.id} className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">₦{Number(w.amount).toFixed(2)}</h2><p className="mt-1 text-sm text-slate-400">{u?.username?`@${u.username}`:u?.first_name||"User"}</p></div><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-slate-400">{w.status}</span></div><div className="mt-4 space-y-1 text-sm text-slate-300"><p><span className="text-slate-500">Bank:</span> {w.bank_name}</p><p><span className="text-slate-500">Account name:</span> {w.account_name}</p><p><span className="text-slate-500">Account number:</span> {w.account_number}</p><p><span className="text-slate-500">Requested:</span> {new Date(w.created_at).toLocaleString()}</p></div><textarea value={notes[w.id]??w.admin_note??""} onChange={e=>setNotes(x=>({...x,[w.id]:e.target.value}))} className="mt-4 min-h-20 w-full rounded-2xl border border-white/10 bg-black/20 p-3 text-sm outline-none" placeholder="Admin note (optional)"/>{status==="pending"&&<div className="mt-4 grid grid-cols-2 gap-2"><button disabled={busy===w.id} onClick={()=>update(w.id,"approved")} className="rounded-xl bg-cyan-400 py-3 font-bold text-slate-950">Approve</button><button disabled={busy===w.id} onClick={()=>update(w.id,"rejected")} className="rounded-xl border border-red-400/20 py-3 text-red-300">Reject</button></div>}{status==="approved"&&<button disabled={busy===w.id} onClick={()=>update(w.id,"paid")} className="mt-4 w-full rounded-xl bg-emerald-400 py-3 font-bold text-slate-950">Mark as Paid</button>}</div>})}{rows.length===0&&<div className="rounded-3xl border border-white/10 bg-white/[.035] p-6 text-sm text-slate-500">No withdrawals in this status.</div>}</div></div></main>;
}
