"use client";
import { useEffect, useState } from "react";

type Plan={level:number;name:string;activation_fee:number;ad_reward_coins:number;daily_ad_limit:number;daily_earning_cap:number;task_min_withdrawal:number;affiliate_min_withdrawal:number;active:boolean};
type User={id:string;username?:string;first_name?:string;last_name?:string;activated?:boolean;account_level?:number|null};
export default function PlansAdmin(){
 const [plans,setPlans]=useState<Plan[]>([]); const [users,setUsers]=useState<User[]>([]); const [search,setSearch]=useState(""); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState<number|null>(null); const [userBusy,setUserBusy]=useState<string|null>(null);
 const [channel,setChannel]=useState(""); const [group,setGroup]=useState(""); const [popup,setPopup]=useState(true); const [communityBusy,setCommunityBusy]=useState(false);
 const load=async()=>{const r=await fetch("/api/admin/plans",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setPlans(d.plans||[]);else setMsg(d.error||"Unable to load plans.");};
 const loadUsers=async()=>{const r=await fetch(`/api/admin/users${search?`?search=${encodeURIComponent(search)}`:""}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setUsers(d.users||[]);};
 const loadCommunity=async()=>{const r=await fetch("/api/admin/community",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok){setChannel(d.community_channel_url||"");setGroup(d.community_group_url||"");setPopup(d.community_popup_enabled!==false);}};
 useEffect(()=>{load();loadCommunity();},[]); useEffect(()=>{loadUsers();},[search]);
 const save=async(p:Plan)=>{setBusy(p.level);setMsg("");try{const r=await fetch("/api/admin/plans",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to save plan.");setMsg(`${p.name} saved successfully.`);await load();}catch(e){setMsg(e instanceof Error?e.message:"Unable to save plan.");}finally{setBusy(null);}};
 const update=(level:number,key:keyof Plan,value:string|boolean)=>setPlans(ps=>ps.map(p=>p.level===level?{...p,[key]:key==="name"?value:key==="active"?value:Number(value)}:p));
 const setUserPlan=async(u:User,activated:boolean)=>{setUserBusy(u.id);setMsg("");try{const level=activated?Number(prompt(`Enter plan level for ${u.username?`@${u.username}`:u.first_name||"this user"}:`,String(u.account_level||1))):0;if(activated&&(!Number.isInteger(level)||level<1))throw new Error("Invalid plan level.");const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:u.id,activated,account_level:level})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to update user plan.");setMsg(activated?"User plan activated successfully.":"User plan deactivated successfully.");await loadUsers();}catch(e){setMsg(e instanceof Error?e.message:"Unable to update user plan.");}finally{setUserBusy(null);}};
 const saveCommunity=async()=>{setCommunityBusy(true);setMsg("");try{const r=await fetch("/api/admin/community",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({community_channel_url:channel,community_group_url:group,community_popup_enabled:popup})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to save community settings.");setMsg("Community popup settings saved successfully.");}catch(e){setMsg(e instanceof Error?e.message:"Unable to save community settings.");}finally{setCommunityBusy(false);}};
 return <main className="min-h-screen bg-[#080d18] px-4 py-6 text-white"><div className="mx-auto max-w-3xl"><a href="/admin" className="text-sm text-cyan-300">← Admin</a><h1 className="mt-3 text-2xl font-extrabold">Plans & Community</h1><p className="mt-1 text-sm text-slate-400">Manage activation plans, assign plans to users, and control the community popup.</p>{msg&&<p className="mt-4 rounded-2xl bg-cyan-400/10 p-3 text-sm text-cyan-200">{msg}</p>}
 <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-lg font-bold">User plan management</h2><p className="mt-1 text-sm text-slate-400">Activate a user on a selected plan or deactivate the user's plan immediately.</p><input value={search} onChange={e=>setSearch(e.target.value)} className="field mt-4" placeholder="Search username or name"/><div className="mt-4 space-y-3">{users.map(u=><div key={u.id} className="rounded-2xl border border-white/10 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{u.username?`@${u.username}`:u.first_name||"Telegram User"}</p><p className="text-xs text-slate-500">{u.first_name||""} {u.last_name||""}</p></div><span className={`rounded-full px-2 py-1 text-xs ${u.activated?"bg-cyan-400/10 text-cyan-300":"bg-white/5 text-slate-400"}`}>{u.activated?`Plan ${u.account_level||"?"}`:"Inactive"}</span></div><div className="mt-3 flex gap-2"><button disabled={userBusy===u.id} onClick={()=>setUserPlan(u,true)} className="rounded-xl bg-cyan-400 px-4 py-2 text-xs font-bold text-slate-950">{u.activated?"Change Plan":"Activate Plan"}</button>{u.activated&&<button disabled={userBusy===u.id} onClick={()=>setUserPlan(u,false)} className="rounded-xl border border-red-400/20 px-4 py-2 text-xs font-bold text-red-300">Deactivate</button>}</div></div>)}{users.length===0&&<p className="text-sm text-slate-500">No users found.</p>}</div></section>
 <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-lg font-bold">Community popup</h2><p className="mt-1 text-sm text-slate-400">These links are used by the channel/group popup shown to users.</p><div className="mt-4 space-y-4"><label className="block text-sm text-slate-400">Telegram channel URL<input value={channel} onChange={e=>setChannel(e.target.value)} className="field mt-2" placeholder="https://t.me/your_channel"/></label><label className="block text-sm text-slate-400">Telegram group URL<input value={group} onChange={e=>setGroup(e.target.value)} className="field mt-2" placeholder="https://t.me/your_group"/></label><label className="flex items-center gap-3 text-sm text-slate-300"><input type="checkbox" checked={popup} onChange={e=>setPopup(e.target.checked)} className="h-5 w-5"/>Show community popup</label><button disabled={communityBusy} onClick={saveCommunity} className="w-full rounded-2xl bg-cyan-400 py-3 font-extrabold text-slate-950">{communityBusy?"Saving...":"Save Community Settings"}</button></div></section>
 <div className="mt-5 space-y-5">{plans.map(p=><section key={p.level} className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold">{p.name||`Plan ${p.level}`}</h2><p className="text-xs text-slate-500">Level {p.level} · {p.active?"Available for activation":"Hidden from activation options"}</p></div><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={p.active} onChange={e=>update(p.level,"active",e.target.checked)} className="h-5 w-5"/>Active</label></div><div className="mt-4 grid gap-4"><label className="text-sm text-slate-400">Plan name<input value={p.name} onChange={e=>update(p.level,"name",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Activation fee<input type="number" value={p.activation_fee} onChange={e=>update(p.level,"activation_fee",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Reward per ad (coins)<input type="number" value={p.ad_reward_coins} onChange={e=>update(p.level,"ad_reward_coins",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Ads allowed per day<input type="number" value={p.daily_ad_limit} onChange={e=>update(p.level,"daily_ad_limit",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Daily earning cap<input type="number" value={p.daily_earning_cap} onChange={e=>update(p.level,"daily_earning_cap",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Minimum tasks withdrawal<input type="number" value={p.task_min_withdrawal} onChange={e=>update(p.level,"task_min_withdrawal",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Minimum affiliate withdrawal<input type="number" value={p.affiliate_min_withdrawal} onChange={e=>update(p.level,"affiliate_min_withdrawal",e.target.value)} className="field mt-2"/></label></div><button disabled={busy===p.level} onClick={()=>save(p)} className="mt-5 w-full rounded-2xl bg-cyan-400 py-3 font-extrabold text-slate-950">{busy===p.level?"Saving...":"Save Plan"}</button></section>)}</div></div></main>;
}
