"use client";
import { useEffect, useState } from "react";

type Plan={level:number;name:string;activation_fee:number;daily_earning_cap:number;task_min_withdrawal:number;affiliate_min_withdrawal:number;active:boolean};
export default function PlansAdmin(){
 const [plans,setPlans]=useState<Plan[]>([]); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState<number|null>(null);
 const load=async()=>{const r=await fetch("/api/admin/plans",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setPlans(d.plans||[]);else setMsg(d.error||"Unable to load plans.");};
 useEffect(()=>{load();},[]);
 const save=async(p:Plan)=>{setBusy(p.level);setMsg("");try{const r=await fetch("/api/admin/plans",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to save plan.");setMsg(`${p.name} saved successfully.`);await load();}catch(e){setMsg(e instanceof Error?e.message:"Unable to save plan.");}finally{setBusy(null);}};
 const update=(level:number,key:keyof Plan,value:string)=>setPlans(ps=>ps.map(p=>p.level===level?{...p,[key]:key==="name"?value:Number(value)}:p));
 return <main className="min-h-screen bg-[#080d18] px-4 py-6 text-white"><div className="mx-auto max-w-2xl"><a href="/admin" className="text-sm text-cyan-300">← Admin</a><h1 className="mt-3 text-2xl font-extrabold">Activation Plans</h1><p className="mt-1 text-sm text-slate-400">Edit plan names, benefits and withdrawal minimums. Changes apply to the activation options shown to users.</p>{msg&&<p className="mt-4 rounded-2xl bg-cyan-400/10 p-3 text-sm text-cyan-200">{msg}</p>}<div className="mt-5 space-y-5">{plans.map(p=><section key={p.level} className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-lg font-bold">Plan {p.level}</h2><div className="mt-4 grid gap-4"><label className="text-sm text-slate-400">Plan name<input value={p.name} onChange={e=>update(p.level,"name",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Activation fee<input type="number" value={p.activation_fee} onChange={e=>update(p.level,"activation_fee",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Daily earning cap<input type="number" value={p.daily_earning_cap} onChange={e=>update(p.level,"daily_earning_cap",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Minimum tasks withdrawal<input type="number" value={p.task_min_withdrawal} onChange={e=>update(p.level,"task_min_withdrawal",e.target.value)} className="field mt-2"/></label><label className="text-sm text-slate-400">Minimum affiliate withdrawal<input type="number" value={p.affiliate_min_withdrawal} onChange={e=>update(p.level,"affiliate_min_withdrawal",e.target.value)} className="field mt-2"/></label></div><button disabled={busy===p.level} onClick={()=>save(p)} className="mt-5 w-full rounded-2xl bg-cyan-400 py-3 font-extrabold text-slate-950 disabled:opacity-50">{busy===p.level?"Saving...":"Save Plan"}</button></section>)}</div></div></main>;
}
