"use client";
import {useEffect,useState} from "react";
type Wallet="rewards"|"referral";
function formatData(mb:number){return mb>=1024?`${(mb/1024).toFixed(mb%1024===0?0:2)} GB`:`${mb.toLocaleString()} MB`}
export default function WithdrawPage(){
 const [initData,setInitData]=useState(""),[wallet,setWallet]=useState<Wallet>("rewards"),[balance,setBalance]=useState(0),[referralBalance,setReferralBalance]=useState(0),[phone,setPhone]=useState(""),[amount,setAmount]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const tg=window.Telegram?.WebApp;if(!tg?.initData){setMessage("Open ViewCash from Telegram.");return}tg.ready?.();tg.expand?.();setInitData(tg.initData);fetch("/api/telegram/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:tg.initData}),cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load data balance");setBalance(Number(d.balance_mb||0));setReferralBalance(Number(d.referral_balance_mb||0))}).catch(e=>setMessage(e.message||"Unable to load data balance"))},[]);
 const available=wallet==="referral"?referralBalance:balance;
 const submit=async()=>{const mb=Math.floor(Number(amount));setMessage("");if(!Number.isInteger(mb)||mb<100)return setMessage("Enter at least 100 MB.");if(mb>available)return setMessage(`Insufficient data balance. Available: ${formatData(available)}.`);if(!/^0[789]\d{9}$/.test(phone))return setMessage("Enter a valid 11-digit Nigerian MTN number.");setBusy(true);try{const r=await fetch("/api/data-redemptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,phone_number:phone,amount_mb:mb,balance_type:wallet==="referral"?"referral":"tasks"}),cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Redemption failed");wallet==="referral"?setReferralBalance(v=>v-mb):setBalance(v=>v-mb);setAmount("");setMessage("Data redemption submitted successfully. It is pending fulfillment.");}catch(e){setMessage(e.message||"Redemption failed")}finally{setBusy(false)}};
 return <main className="min-h-screen bg-[#080808] px-4 py-6 text-white"><div className="mx-auto max-w-md"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-yellow-400">MTN • ViewCash</p><h1 className="mt-1 text-2xl font-black">Redeem Data</h1></div><button onClick={()=>location.assign("/")} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">Back</button></div><div className="grid grid-cols-2 gap-2"><button onClick={()=>{setWallet("rewards");setMessage("")}} className={`rounded-2xl border py-3 text-sm font-bold ${wallet==="rewards"?"border-yellow-300/40 bg-yellow-400/10 text-yellow-300":"border-white/10 bg-white/[.03] text-slate-400"}`}>Reward Data</button><button onClick={()=>{setWallet("referral");setMessage("")}} className={`rounded-2xl border py-3 text-sm font-bold ${wallet==="referral"?"border-yellow-300/40 bg-yellow-400/10 text-yellow-300":"border-white/10 bg-white/[.03] text-slate-400"}`}>Referral Data</button></div><div className="mt-3 rounded-3xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">Available MTN data</p><p className="mt-1 text-3xl font-black text-yellow-300">{formatData(available)}</p><p className="mt-1 text-xs text-slate-500">Minimum redemption: 100 MB</p></div><div className="mt-4 space-y-3"><input className="field" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,11))} placeholder="MTN phone number" inputMode="numeric"/><div className="grid grid-cols-4 gap-2">{[100,250,500,1024].map(v=><button key={v} onClick={()=>setAmount(String(v))} className="rounded-xl border border-white/10 bg-white/[.03] py-2 text-xs font-bold">{formatData(v)}</button>)}</div><input className="field" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,""))} placeholder="Data amount in MB" inputMode="numeric"/><button disabled={busy} onClick={submit} className="w-full rounded-2xl bg-yellow-400 py-3 text-sm font-extrabold text-black disabled:opacity-50">{busy?"Submitting...":"Redeem MTN Data"}</button></div>{message&&<div className="mt-4 rounded-2xl border border-yellow-300/15 bg-yellow-400/[.06] p-3 text-sm text-yellow-100">{message}</div>}<p className="mt-4 text-center text-[11px] text-slate-600">Your request is recorded for MTN data fulfillment.</p></div></main>