"use client";
import { useEffect,useState } from "react";

type Wallet="rewards"|"referral";
export default function WithdrawPage(){
 const [initData,setInitData]=useState(""),[wallet,setWallet]=useState<Wallet>("rewards"),[balance,setBalance]=useState(0),[referralBalance,setReferralBalance]=useState(0),[level,setLevel]=useState<number|null>(null),[minimumTask,setMinimumTask]=useState(0),[minimumAffiliate,setMinimumAffiliate]=useState(0),[bank,setBank]=useState(""),[number,setNumber]=useState(""),[name,setName]=useState(""),[amount,setAmount]=useState(""),[busy,setBusy]=useState(false),[resolving,setResolving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const q=new URLSearchParams(location.search).get("wallet");if(q==="affiliate"||q==="referral")setWallet("referral");const tg=window.Telegram?.WebApp;if(!tg?.initData){setMessage("Open ViewCash from Telegram.");return}tg.ready?.();tg.expand?.();setInitData(tg.initData);fetch("/api/telegram/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:tg.initData}),cache:"no-store"}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to load wallet");setBalance(Number(d.balance||0));setReferralBalance(Number(d.referral_balance||0));setLevel(d.account_level?Number(d.account_level):null);setMinimumTask(Number(d.withdrawal_minimums?.task_balance||0));setMinimumAffiliate(Number(d.withdrawal_minimums?.affiliate_balance||0))}).catch(e=>setMessage(e.message||"Unable to load wallet"))},[]);
 useEffect(()=>{if(!/^\d{10}$/.test(number)||!bank){setName("");return}let off=false;setResolving(true);const timer=setTimeout(async()=>{try{const r=await fetch("/api/withdrawals/resolve-account",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bank_name:bank,account_number:number}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Account could not be verified");if(!off)setName(String(d.account_name||""))}catch(e){if(!off){setName("");setMessage(e.message||"Account could not be verified")}}finally{if(!off)setResolving(false)}},400);return()=>{off=true;clearTimeout(timer)}},[bank,number]);
 const minimum=wallet==="referral"?minimumAffiliate:minimumTask; const available=wallet==="referral"?referralBalance:balance;
 const submit=async()=>{const n=Number(amount);setMessage("");if(!Number.isInteger(n)||n<=0)return setMessage("Enter a valid withdrawal amount.");if(n<minimum)return setMessage(`Minimum withdrawal is ₦${minimum.toLocaleString()}.`);if(n>available)return setMessage(`Insufficient balance. Available: ₦${available.toLocaleString()}.`);if(!name||resolving)return setMessage("Verify the bank account name first.");setBusy(true);try{const r=await fetch("/api/withdrawals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,bank_name:bank,account_name:name,account_number:number,coins:n,wallet_type:wallet==="rewards"?"tasks":"affiliate"}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Withdrawal failed");setBalance(v=>wallet==="rewards"?v-n:v);setAffiliate(v=>wallet==="affiliate"?v-n:v);setAmount("");setMessage("Withdrawal request submitted successfully")}catch(e){setMessage(e.message||"Withdrawal failed")}finally{setBusy(false)}};
 const isReferral=wallet==="affiliate";
 return <main className="min-h-screen bg-[#080808] px-4 py-6 text-white"><div className="mx-auto max-w-md"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">ViewCash</p><h1 className="mt-1 text-2xl font-black">Withdraw</h1></div><button onClick={()=>location.assign("/")} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">Back</button></div><div className="grid grid-cols-2 gap-2"><button onClick={()=>{setWallet("tasks");setMessage("")}} className={`rounded-2xl border py-3 text-sm font-bold ${wallet==="rewards"?"border-cyan-300/40 bg-yellow-400/10 text-yellow-300":"border-white/10 bg-white/[.03] text-slate-400"}`}>MTN Reward Balance</button><button onClick={()=>{setWallet("referral");setMessage("")}} className={`rounded-2xl border py-3 text-sm font-bold ${wallet==="affiliate"?"border-cyan-300/40 bg-yellow-400/10 text-yellow-300":"border-white/10 bg-white/[.03] text-slate-400"}`}>Referral Balance</button></div><div className="mt-3 rounded-3xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">{isReferral?"Available commission":"Available Balance"}</p><p className="mt-1 text-2xl font-black">₦{available.toLocaleString()}</p><p className="mt-2 text-xs text-slate-500">Minimum {isReferral?"affiliate":"task"} withdrawal: {minimum.toLocaleString()} balance</p></div><div className="mt-4 space-y-3"><input className="field" value={bank} onChange={e=>setBank(e.target.value)} placeholder="Bank name"/><input className="field" value={number} onChange={e=>setNumber(e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="10-digit account number" inputMode="numeric"/><div className="field text-sm">{resolving?"Verifying account...":name||"Verified account name will appear here"}</div><input className="field" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,""))} placeholder={isReferral?"Referral balance to withdraw":"Amount to withdraw"} inputMode="numeric"/><button disabled={busy||resolving||!name} onClick={submit} className="w-full rounded-2xl bg-yellow-400 py-3 text-sm font-extrabold text-black disabled:opacity-50">{busy?"Submitting...":"Submit withdrawal"}</button></div>{message&&<div className="mt-4 rounded-2xl border border-yellow-300/15 bg-yellow-400/[.06] p-3 text-sm text-yellow-100">{message}</div>}<p className="mt-4 text-center text-[11px] text-slate-600">Withdrawal amount and account details are verified before submission.</p></div></main>;
}
